---
# ============================================================
# SEALED SECRETS — DEV
# Généré automatiquement par scripts/seal-secrets.sh
# Ce fichier peut être commité dans GitHub en toute sécurité.
# ============================================================
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secrets
  namespace: dev
spec:
  encryptedData:
    SECRET_KEY: AgAppo86idONA0Si51K/iriT6cOvVTdbcKrkqW5C0WMP/gCLy/HOj/WDNo/W6jfAZJYNQYgYM31vJP8KjmXrUnsyE+rzLptD26MYJBRDm93sg7tfs1nc9Yk17u0TdZnRxFa/ay2ezIc8dgogEEqNg18s8ALX967lovza54jXM3n/qvytPxfm7BnSMKWSmUBsjxWjG185piuuXtJxAnzL/dXQgKJtOyLwYSwZZP/xje6pCFXD6uiCXYPww4gTRovHdEPLwcGa/lUjg0oVWpqCt1uv10m+qaVRcMdwlIXr1ExBEAGW80oX2/iJrBAwHCgvQhfF5plfQSiOlW7380L6WXmtegAv96IkZQB+S7sTO8xvQTt+RaIagIwPhEqoX50VxXlF9twOKPdjmTSThzHzdNb/t9KDvvoXDOs6JIcVP5btIpZVjW3HRV7iaNI1+gb60Knsmvwjkx9DLXQVgOYuYFWzw3g82YiuelEhF1JSpqHpaAwq6/MYSFO1SjwEkrheoWgK0v24rXFGEwngukSQa7mU8k6FZ2zzlEYtQNc0/u0rCP1wHT+mc6OzieDceVCt1NGFGb6FaCP60DWd3B9gmbJbXLkLvC51SG+S9SeiGZzhhq/N+onrHWfyaCxz1+bSYrjMVJZRsSFpQrbPuRIDEfBHyJhWoHp+2u5eC04feiYyF5GSaTbhD3Xt7HJIPu1PGBit53eDhx2cTUgwIL0JymRz/xD1m66dEPCo8SP/60vG1h80aj64tzneZuc=
  template:
    metadata:
      name: app-secrets
      namespace: dev
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-credentials
  namespace: dev
spec:
  encryptedData:
    POSTGRES_DB: AgDAgTXvq3PbGKWzzLZVDtEl9QU8w0MOHsKjZlETb4KoLtGtZKCtQeuRQvTdbQ9JR7Gjzi8xVMe4/uIoupPjIc79LbwsgL1EeyosLzsOwqqOEQaopNk+zwAZI+MvNezDvxUcSRhpoe0I+X2G7dir0X8IRKWauAcPjlfrdxe++it7O4iaTsH4hT6T5f41VYmcyRXn4N/lxaqE6eZeSoIr79WK1Om3OGmdGUcNqEXXYTBeIQ0EpIeS3Mm8PK64G2NuS9f5/5+vXdJwecELbe20yxq+/j/LggiRgWC0vluX6YOehaO/KtoPIvfDXnG7UTc9IwxVnTgUy0xO32n2uqnSt2Obo7FsnEpYZ3gYehoHnsDB3SPxluAYqfoTHD8uZp9fSRpOLFWo/NJBCucbFYzP8q+Ta8hLj8yNpbdacAcKeAUHwy9s1yPMGU+g0kB80x0UGSenr0czQFfC7Ebs6pONc6lZ5/KhbF+W41KH+kWUKRFnAfgPk8LdRYwAbAtfp7GKdaKSNA8mm6sOtsiCOWHiaE5Xn04zLgIgPgTNyCTL6yxfSoiuhO0EbHtlt9L0rF8jSjBw1O1dw0o5Xj86/Odwjx+NZH8ksu54MBIHBpq0zWUfHY+KBsWrnrgGXpk9iBgXb2GYKyXC7SfVxy4ZCY/+LVa3WjLXwx4BwJyocBgLeLx+odLchnc6FkWWvM3D6RrcNYX2VBPzhg==
    POSTGRES_PASSWORD: AgC/MX9OEVjRl+LhwLyoMQTe3oqRXq8zjUdJhYO5ged3PZVeEt4YNpdWmLdIBW8jchbUEkNw3nEwnkDeMqtoCSkf1qxih2v/nswUyw7by1tZP8TcvGBxQ6T+MWcrw31T5Ndwhw/yCuxLhADCdkBJak8xiM0Hbfc4w3eSN/v+N30MfK05R0dzl8brGl+eHKth4UfNFuTOYXIZOB46fNH4yAkdy7qZQuu2uYp1goRUprUdZkzdMboFIGu/du2+uhBAZkBJradUUAXpg3XFFRWfahohoPzW88u6UBabhqKv7QSgPxSw2M88eSqcEI2W42GcZ8XeribU5MhuT+pF0moLJB8I7Krghe6xI3aQIU/QGY6IbxKodzAIInyxcAcs25kP8QLPkxWHTcyvB5Pdy7SdmAJ7IUJtfhz680cDZzDN6bLANKaeOtlFSaPuHYIy9irrOP2vadyG7wAIHFVbovB7tKob4daWeB4SxepmBOuS0sjRmv7+hocyjPIAJNldBlsV17DdSNc2JTbHI8K4SQOtqyqLHv+llojyrMqLpWF7DceNFP6eb+0AxNsFfKjXjZHV0XeQOYAOBmjxT23pSD2Eds4fGIO2PhCG/DsZjARXWJQO5w+ATgklAe2VWmLIxd4hRUjmKHc9bXEwzeJewISlGPQh1chC5tHBu6hnRNJNhM9q7SKeM+aKqDXxWW7jul0HBJmwRJJK3pfTGxRuCKkYTa2bUHkvUbMv//exaAGZbrSMIg3z1tRi+U5UujxqUQ==
    POSTGRES_USER: AgBhQ4menJtxPkGFAH8gaZVJ2pcqMUq5iG3QCrPSHd4CGPxLgsnYwESkgef8Tyc1mFyozRXq1AAJUnsuJi8DT6TqjxQUu4RUaGxjjwjKrmZdOjMMmsRcTSgknEvF3hu4Rux3pgMLgVLzBtJVi38vzDDRHpk6SkzQ//9JoEhU3rWDXWO4YcSpUYMy3RZTBsawNtQFwtwY7qw05+1BuNWMlm8HoVoIAqpdHR/f/a2ABTlpcgLIztDmnBv96AjFCbT01X0ggAAENGXs49VnSZ7vfq4nYu/kP0GKy667dAiTRPdNt+GVTqarg7I9G1lz9XjSAk9l130PEowB3FKg2/gBHEouw7jqNNDwjDj2JzcvvXW/FI5Oo3FRseZC3blgvpUhsBPW7dv9yz0bI0b+bTfYEGtomnFj4EsrvTTnQTV3dQdQnpSDqIATPkfMCDkFneETnE1YyDFbKrtwGagfiHjNY+1auNM3cKXPC9dCT7VB7JLPy+byR0nTAe5oX0yRe6QEstt5PHYNRBJKVPWZEjpJ+JQfa1nJVV1gTYchlFgaFlEQ7oF3TYlyl03nsM50JAIzhyFsaYhpHG6AKlkbGsFflDjH7l84NUhx++ZImj4hL7olkk3YUTsiRonfNrxxHdMAGXiNIC9gZfy8XKRXD7JCru+W7mC4Jo2eeCKKG1xFI7j9Bbueimvyx7bT+VG/7KLNHjGMaKepsokUapWx
  template:
    metadata:
      name: db-credentials
      namespace: dev
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-credentials
  namespace: dev
spec:
  encryptedData:
    REDIS_PASSWORD: AgAR54lEq1MHJC9zlQy59afszjn3i/d5EocJp1V3H3CHEy9DoGgSiN5680F3nnog5kB2s8qDa276ZpWIvuBzlF9jobXFiaDo/YewrE0fHBKS1y33jSiwQUMVkpCCXhdVNn/AKc909FoppMYmu8QPtpvBPUSgw6klJrkwzstNlWJDQ+jHODONusdIymvxV9wYP3QfwupX+2hltOBJGc6gO+sD8wYUnc1FC+W+ad9bvOu1UPplnhgerFFdq1AP270YLUSS1IYfVgMjq7GT1VlOw59xj0I6oyAaXiyewWXQ2rItlzbybzQEDhB0PHiHnvGnjfNyqgy5MUKecxNNchxW4jdUryDU8tGS3YHgmHVs3LVadBXCiQSmzYDp514IwUOo45HcB/IA0PYLv57odxwvXpMLjgxDkcvK2dwm1uBEgYaM9OjDgu2NIJKPlhlDXz6+urKBGJYyVEq/SjUOIcz9XeQUpRbCxcjOPDAjZ5JfepFk8KNeDkFQePX7b/DgWPAB7N1yxGLy7HobWq2uca8LjYqV+8I3fmgEYtbK/s5aumbz0LBwFHEfNgDOj/8WGSgBfijIfUXOTgtuYJvTHdTYuToOaVH+q1YFPa7lupsPZO+M+zplAg15dfOazso1JkqVNFmv8mfnBTMZg1bzRr7cgex0chHn5u+M3dm5DG+Ekk1nnwfw2UVGgnFiOAGe4OIt4ZeOJ5a6UQPaOapL9RyF/cWxENgsS7/9wh4=
  template:
    metadata:
      name: redis-credentials
      namespace: dev
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: resend-credentials
  namespace: dev
spec:
  encryptedData:
    RESEND_API_KEY: AgBwZyF5D1pSdSddaLiXav2T4B+PbExWcXza6+tyWxnXDb+1SclxlyQOak7yGr0eITCikD9IB1JJvz7xZLor9LqKKltcqROT4v61YeJugGd3d7qBmXBqjF7Gvr0dowITOZT/qjCnPYfAx6vvddrjLNxDGqth/lUBdpQ9o7xeWtrvDlab6gfpUIU8ywnm8G3OYp1kULzjeynKUpPIdmJJgf1GJF19ZqVHem4fQVe7c62itZRal5NtRgPgR70UvtlFLD8vJBWR4aSzV/oamDB63xYDpS+nDPqLQRQghm/6lVVm/rSkH8s/5/hDk9oho5n2zKSTvPhfwwLHbhuhKUooe0Afd6uKNt+pbD170Z+nVBrMiUEAzHpgcNG+It2GiHXUSE+FubnXTSZwRviiijP1KqmHaL5/BhniC92+rgfT8NK2Nw0ykS1phh79K4MixJM9nZSduQdoqbe2T1LPMOIc4N1vwN7VDKMjomugcOEemLQp4hdE65Eva3mQPdHASSlBrsW76ooSkaqZrNsSEq87qAwj8Ov0w20UFgDy1durYXqgSWuYCizCGuZJjMBH7JUseU1kSzbWDlPhYEmoqhwoL4P/B8zrw1iMRZzkjGktkchAIGvvKgjgVUwin5QNSrs44MgaDT3xCIQXAZFAihIQ2UmauyAkdWXF2H0B0fg0kt4kPn/1LLqfxbnqpLZvBhRnsnqdGvemgt4MRcgSq9Fzzv3ouz5Ucv691S6CQnua+yZQ5jFjShY=
    RESEND_FROM_EMAIL: AgCLS0SMPnaLc1TFMe0hKaoMYLjkYbs27IvjpgZ6F77PshQNhP5dSRHDpLuZ31HZdaSDfC7gq3+JkD5sfpUaRZTYnvhX3r+WFgvw1D3acFQ+9BfhGAqtdp2pWcHjj+lZ1yFxzgz3vIxM18Kl8z1crnSmgg0+jldzu97Q/sfTwLZwILQzjvWEA0n8Qx6+CE2RHIhGF/nsmrxK38zmLcM2o85w/FMlCJPrTdXomJsILamh9QbbFUjdF5/v9mC7eteEVHY+CXzrpZ62DDrmvByC1bku+ttMZdrAvamFrNW05L59I/bPYatefQ7F23TSOaiohCsI8ZL0rmowi0rAoq2113D4nOmdEz98Mg9lZXZzYZvso0J1e325L00d7BTvdCIjNlwAOGeXjEPaVtVHNS4Ik8eA2yTyWZPJiHACzQgFpZDV6bGkpoieTiixypleLHbCMfqQ/ie9JG9KOzIx8ut2DPHGt8WMx3ep8cUyNw4HUpc//79Jrfj8Lzpq7mQJMIsuXFeg8+SJHyhh2HKB/Lm/gQSZPLWnlqZ1vEan6Yc8A1tRz93B4clYn0UsSobdD92O6/IXJ21srlcxEW7xHwacPPJ4LquaFXXh49JwFr6s3T/wfLDVX1cBPFYCcAaR5m2AipAJR6qb1zHxNpDyOGHbyn1U1fjhDty1Apfyq+CF0GlQ3qpwysWC5O28+ETvlhy802VS7gpo8vJY/j1c67RizCrRGjWS9+JX05wxrBYebbpy3puO
  template:
    metadata:
      name: resend-credentials
      namespace: dev
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: dev
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgBRM+7M4w+o5CPQ1rwV1ZB+oHzZtc9PT3i+l1UZoHHpvxhClULFvgsGO5OtYY95iLfKdPpJFcVUc0Zr9zvh1MfHZUDURppp+gkqtbxZrmGKp/OKm/4PR1iZo7SNjCRfuSgg+YogV95gAEQAVmmqwM+vbZA8LGvqv4L85lDyoPHBXOPIDbYYvOQodL4wSvCzg2PoDA80D4qQ3lBh59p0jIpzVaKBfacZ4SCbf4/TsE74ymeY7R+4E213hleu6Adnb5xFtKexpd5cpLcXGjBCGpdNxYutViVcByZ3BVgYmz05G0e9OZjKoUQt9EvnZurl290e//aZcznUyKN+Upym/3ZFN9IGKImj7r6II+3ieZUJVcXTx9Utr0r8Omo+BzbeC/AUy/3GhLe8tdV9vZavUuAnvqnM1GBfqbWess6FR05yWU70sAyvRBJjymj8xS4IhgxgaVqHeJj9g9cXaAxC/2RgaPd0xkDtMRXRWLmwKvJJLXoJrJlBlfSU5QinqLNYtk8qT6ui3dkMUeQBcJ7sI4rgltT7PZAavE1p0K7wZTUBPtDbvCo50HlOqyAZohgX7vl+1VteH3032ahcpSdgAAgc0wdkzRSjRWEdFLbpOGFfsu3917s/fV3hHBh53oZNyElJ3EFl1MNYLexeSu23HA9fhf9dhDt9pyTyuHcIsFwYN6dMgIraicXDwcTuDf737t2g/0hExy0eawcYWqw3bmte7yoo1WfZ4Lk1jGBmHs1BL5qW2zjg
    MINIO_ROOT_USER: AgAH9VHYAttejoa3zY3PfXMePlIO8ePceUAuOpP0OdFc80b/p2tCQtTqowiZBq7/wL8xHVMRqZ6atb4qsAmKsxXz7VIfd76hSlg/UjY0D52heZSPSrdqSqHO40BVkoQiJ+XNzaHXyF/zDx/y4SPesXm6vgIfXWit3zUrqkdPxfmJRiex5TNOurlwBlJU/uPqgaiDngWGGeBjAD42typIngccTy2n7C5mI6ARzCMiO6fKSqR+8SrE2JWcV9zxls8jLkCEMuaLRei1zW+nmnCfz88QB2dKIC4fVdCoDJpyTOIp3c80zGroduIHn9SYGz6zc7QFfrGLxbRKzsTO5NBrxwIz29sHkNlMVs5uJz8MeWRSqqbEKvnqDPvlw0eWU6NTbtR782u12EYHzlMsCUkqlbmQKxZNt8B25m39kvqjbLLaCN3R3ja0RMD6YzFoLqKpkOB+B1tIwuSx/JeH0ze2GuFkUDvBcMKjn/uDwi+AU5fGCXnnuYLO8EQepS/I17CfwGIWm8OTMMjyKw9WsQ4xEJduHdtX3P3FYo//R99HSpOubnw2zE9NgDgrCHWjhknxVxgiNtbqwmKM4FlorCx9iUZNxajIP2sFBK4IsR3mlJI7nUC6rzBRTPu9/T/vWnupaxqxPYN9fNMZBoZTeAagewbiVmPG/IJ32TQi13PlEDJX+labomECFtFjGc+71i4p2I0r5YMuwIpvyoRwBEPNRDPIuA==
  template:
    metadata:
      name: minio-credentials
      namespace: dev
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: dev
spec:
  encryptedData:
    .dockerconfigjson: AgCBsL19ZRKy/9jT/NbgwsCDhU4V48aQxyRb98i2SV5aoK0QMRI/tinMiuzPplhSRD5igQ7LNybuuensrHGDTev2v48MNV55vxlIP4BVT83+iqfvGyX9XdsxCGavuE3wChPMoouIjYYQo3r4Y8boFxtSvixKoL4iiTzo+3WgtuWU7WK4mjrwXrWp9/kn5Ee0AjyrCnbmFve7jEg5jC+1doMSJ1s3XGxaEvdLA+OZlcG2hImzJFRtj0sqsjXEl7kZd/1LusF7HLzPnGsNaGBf39na/7RI+/nXMDLu+grib2ipGxGF2wXtjKCiVh/ac7ngLMPJ5QH2E+JkmUWcE5p+ZjKXQ9N8pIJCYbDB1synhv5N8KAmRLPmjs4Kw9soAJo0PQfWmX/3zbyA/DGfQmAdDaQZy+pLyRhxLyn/OzJX0yIo6JNnpmannIk+jbMYNw8ny8w7B3A14OZ6U/TTtiweJjw0p4flIF+qB34N2ysxbjS8JzKJVDG6gin+nTt01SaznRxkxP+2yRPC4Jv1S/5IUaK3+L0zN5kUkE4aBtiH37XtWwaRAwh1Fz0PlFipla8X93zOkoWEMS+R2uCIYjQUb/aeuqr/GMu/HfQpbCP+FIU2h76fEYLwoc610LXqVdzFjeCq+QtD6BHnnZBEi4O0QAPI1Ufs7k/ATuigpPFe/kb4DIV+xlKOdJ5/AOMQpu17V0sojV33FFfo5F6S7ZwUeZ9tus+cFwrdoRkMmNVXwWFcjSPiNiEN2U66BnIcEZCyoKvaejqVJoZz3jKmRL0MjgCOaf9J4k8q1kiHDd4LEngepjNzWDgFqdNV8dfNxpv9/LLa8PCxYuF7oNyEjwgHSW7K6Yk9VTt+vIt0OtUwnRscsFlk/R/Tl6mT1kJP8HyO3IgJnhxbXJZfGbtwGVCnIEuObg1VyTVJnBMISq/lM8VPwwfbki3pdYkH0wCC6F1uT2hKYV+yhm3GUz/qJn4ZtsJuKRr7TD2U
  template:
    metadata:
      name: ghcr-secret
      namespace: dev
    type: kubernetes.io/dockerconfigjson
