---
# ============================================================
# SEALED SECRETS — DEV
# Généré automatiquement par scripts/seal-secrets.sh
# Ce fichier peut être commité dans GitHub en toute sécurité.
# ============================================================
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secrets
  namespace: dev
spec:
  encryptedData:
    SECRET_KEY: AgBDceMYi60NvBoLvzrtAi/shI8LwXV2HdPRkCC9GPPxC/mq+gjX7NVufKAh2NlHUajIlfXGvx0U91SKW9bD4W6ZEfzvdmVYjPCu6YP8GQl5WtjuORGBW43FT1NYAo2K38HBMp9Dx+76ufzulGJwOUEqG70QSYFeHKhz5x2fT2xKRub8ugv1hSDk6uAUcRmOa0deXLcE6T4pMDWNmt1tEjPqEls0F/VQevnB1DyNHchKzPqNhosXEYQaLr6XT3Fq/2ejVok7BY8/mNTIL6v8A5bxFpt4wFNb/fI4O6PjsCir2nL1sjepTrBGfEsMCRuFPMgEqImM3pD2JQYfaV3VwtSK9kD/YJwsJpTjD9GM7+kQepgLrLoWchy8xp/nWNfDavmUQ4/nVaNxvW9d40UlS4AAHjPVQGQ9wrrqkgrPG6yPLbwZr5k4SIgLi3jWRPn8oOSIWxvzrpTeUeccn3bhAH0cKWkyjsCq/o1LdiIlWVNNuuho16nu4I/pNHnqb7UjEcCx9+JOXCw7MYKD1ta2SF3sVCsrN3n/2JuBOp1SBLP4eljCkAOt7Eo6aRSIeED9l1dZl6VCdMaiLxheHwRdvgcYAJrQhv+CNVea9YBrOdK1CzysJ8GWP9CJIIjHtfLDtDo4Grs1tGBlLkM/MbzjLwDyCfzIbq5Qct+EFFJjjjCVxMGqqetvW4GT4ufxHurWKXDB2B1CfqgGjt+nYu1fqsmGwAZew+2kB/K38Zy1jZEsxwXv2RYWIaz8JKU=
  template:
    metadata:
      name: app-secrets
      namespace: dev
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-credentials
  namespace: dev
spec:
  encryptedData:
    POSTGRES_DB: AgBE7odWgIOGXYbaOYpPeYrjFsW8ITEaXiVTiMWDa9rDs3NumNvSY6mem6r6ktpl2JdT+pozMYSKp4rhCjfoe/FcdTbJRXaksTWaKrdg6e8nERr9oDIAkmdfmOb8RUkF4jeRR15OFhFKrYiPQ5s9cVMZjMQt/40vQEIQwVK3rOBiJecoOBX5U5NTJREsM5UOkebF249VVnkOd8m/PcFPpR2exODDygdDOVjQge7W8KC1cl9TyKWI1gYQJ48QgvQjxWfJHu35TdilqEG0sBAcxVl+zWatAoPlVq6d8fhyeV4gP109eXGZKBHXcf1yAx5emldq+y+RbXUJwpg9myHZxKvlkag96N8uG2/clgYxnLkOR7wVIyAAoEHcAWj9IMahA6nimAQA0RP2W+gsl8aMdbmk1l25zbsT2rYi2t8/6dZDGJNsJnB6Pb4bRYGgXIGAbo3U+PFFhQ2o1aoqK5qFKBS4yUAtRyXnU3FJmGvJHyBdq3locvuW/LwRsA9MSwCDVEX2V9RV6HslZC/uSm2gevbdlO0zK3IemjLbMvJo7keCfjpUFHpb1uShtCQEObflJHgsq1QyPFmd3pPjT53QXxTISQwNDX4LOcBYRqZlzdmgiUdNBvpWQNyHpZ/3TymcMuZuqz3VO5RpmBnMcXPrXa7EPSVGAsn3lDi7dAAim/BtIKwtJbOgoM7pZErDRgCtqyqVDQQ3Sg==
    POSTGRES_PASSWORD: AgDUQwjnz7GdfLPahWNNKEejZJf83chvrTWsKw5Gv084AqX9DVdGjbEAf5VNQHmiurz9Le60Pd9VJFZ3HjS0pbEcB7b1nwxeCqp9kXX8Mo4gArWUxxf8+9cq3y29HCLb24wkAzF1INp54J9dCIuOPCtEOp+KGF6ydwbCyRbL4FaIjJRwYyC70j4z4oUgJN1u4fPKV6UhwGfTVyN2Ht6w0P/trCcF/3j5hsO7Tj/0HARQ+g5zXlIXJueXHbT/XwcBMgk7Qr+rU5Yur2GnyVkAguWib1PmsAqefUnpokUZekIDyYLZjNqF5kyOWvXnr+Z2W84oLDSogDiZpEgwUQu32uA+G55fKKsBAexSeBu6i5IbiPF/CePt9c+uF2i1sF0QVrUdKvhtqP1Xa7rD0Zu2rbbB+AwP6TmH/qx342ToFm9FgW2TJkszuJzlpEWIPPxvM1iJm30CvCHWkN5dAuJUKyMlyEQlKQD2ArXoiKMTB9d5RdmXL1dIc6jD+V9oDt6+wHT7I049vsZgYviC8jotFLhnvAgnM5xbK6EN7a58eqvXdQ3V0Seyx4G18AFqAcP0k8tNBn6INsVamrcwXK1LUd6vg1gBJUZi8sg6izNhyu/MNdJ0T5sL5MeDzkc1Q3+mw+VKxr9CiTmvCiih7t9n+I0sdA2IRbQyi8Gps3lp4b2OhNHj69E7rxPJ9QfG8/a6OyR6uLPd0w1fOfJMeG9x3zQAjjNsaCQyc8yFpL3mrIkVUmhQWrI5tNBBTlvI/Q==
    POSTGRES_USER: AgDbCRgem05Dh/ovdigTzvjMadTJxTpb0IGh2ij8m+eDXwSiBJUpctCaPgwmHKbCJev0ZrHjJIZSmSKq1ktkpdAvsp14ODFLnZ9ZtROZcR4faAnG/eTAS2KQEgIxK1gI4x57+NgaoyL/Pw9RNAWlWlO6pylz0QJl82m2Bfh09uzxbDPY9InyZKYLseg1N/aK1HhP5S9MC9env/zIuvf01T3w7fuVXYY0C0JHtu+soBCj5R79kZuqA/yHwc8RgkwQgZpvQG2aepsSUjMHKE/jPGzRBbwLcPsvT8PCcC2wNrlit1gX5WhHNT5smwxkc4+PFWnqr1vb4eaT/uZcZtzpDd77WXQPefphCbovXEw/+qBDjIFuKig+6scKbjHU0ItL7OqomRJk5diGRZ7Dakoog7oC33W8AxTJcmRLfjEyaRNFLS/U3YBdMI4bcgpHa3+sX7/wuZs/whJos3pny8xlF0ueJwLCN3N9eHf7HDV52rGzf5814xBzFC3srfTnqdR3GBxqRGx/lSOxHRwqFMHaAf9yCNAnxt7R0DWIk5yoJJzr3B+08EjFTAQeAHk3Rf/YnPCedpHt8aSe82kJegrEl9FzFYbCeLHam3cQ7Y60DwznegOSIAxhMa3bssOuTHFG6cqXL1UuOi+Z+QLIsMyMv3VqZkgjPvMQGeS7QU6WdzzagwvkF8iSd93iHRdf7b8U1isVgnfUeVlMUfle
  template:
    metadata:
      name: db-credentials
      namespace: dev
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-credentials
  namespace: dev
spec:
  encryptedData:
    REDIS_PASSWORD: AgDOL+S1Vu7vl7n/g+1Lhm2jR2sWFypbidkNVpohkHf1Hc/t7Fv/KBopCGTasvkqduTao8HAvO1uHy52ZjOD9pPQMADHQJVH/4DI2aLKcnEiN5RkRWRbb5aMGdsrxg8xes5b0v3nc6c+egUhp4kXafDrkCvMRdhUjggSfEwAir5Na/UhWzWdXkV3azvMQYYgXGAF0HaRqMOJoUeuF3kcN5PXZVA1odqRJluFjPCcfDi7bHWqULNMZmD1zSttGTJf3ZMPsxDZykpH839Zt5j2IqeMUmTnNmVq6JEAhhC74Jy4GPM25aFtiJxoSZWLCJPLYTUZQbkZJl6RVt4QHYlfd1zkYDbS5H68fxeSj+/1Bes0LVcWjcvxvZo+fUd+ihKb0PuJL9XymmR5FIvTGcJMmJdwvTOUZZEcA79+czSRglB1JxI2+i+eZw1ssGkPFPqLbRVBGVYvAsyMhfRqB1w48onTzeW4tPBslYdkRt1V226TJpEV2fsCsjVON6GC8hV11cclNSpSHFpDqnPhrfy3ihtHdeMYZdNp/67AzMqiKJA5dOC739RiT0PhRIO+Qd/KaGPcSS2xJmZqaYT3qTKc1EHPhjfWe0AzcY/WrwFYDqNkqFwOWoUwZGzZYv0iTqnOCoyi5qL+Q23Jj/eDLvzylHNjBVrHO778zshiLpalnV06dz6UB0EsD8JAhMVPPn3QqMy85OURE63MMVcBT0m2vK19L5PhWX13muQ=
  template:
    metadata:
      name: redis-credentials
      namespace: dev
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: resend-credentials
  namespace: dev
spec:
  encryptedData:
    RESEND_API_KEY: AgCmpZlVqmi4ZhuDudsUayX3FDGlMYtxqoQOStmPoeqbgRp1SgclzMlerI7ajzhLRkJpO1fvi4Q4G6Wpey+vUNTeJoUTg0jNFusvUSkBY/yciwm65O9wlIOl297Eonly7rPr6T2c+0id0BfgUXpuwLeeULKrlOxn9wEkjJc1VgKrGeEkknRDB3jgZXD5ds07DJfNS+eri8xed+CHrGkYrRIgk8WrYLmAj8CjomTsRtLy4lC4F/3dX9ZWMA3cPTVqBhiUsPzXKnewvNd7xGb8CwYhnI6ig5nXUNDNZ3CVMl6BNZf3eN75+giYVoDy22fRAndOZ6wi80vhsjxux3YXZ0C0VRuLWg9DVlAgd6K5UM6hyYzFkS7aBJrqnrAcXm1CBkhn1tatZ7s0CM9jTilQDBuDB1R8seJ08BNG+XQA+S/ZJwK3b27GKoNTnophHXec5rzXV5xZOvoC4QWFX5K429Uh7XhJFjyYbyC+1iz1HyXovYRaAY+xuqTma4MYMtgh8RCp9L8OAsyEr9Ydg0rbISdQ8qb8BY7qWhmhyIEPxmszZrgRixL1FXEBWniV1d1Q2KH62D58PmytjHbPaSJr1J29/LXJLpX3v1AdU7DfsPFRXz73qbXONH0RgOArcUN1jkWPJkgSxDKcxkyIaugMnCCV8ZYysj3I6uRjUwYM46L8Xw0IRmFFHh9VWm+emEs14MzwaI5NpoHrt81j5cgmSxmkoW3vGcAXswZdcEq+/V4gJLg7b4g=
    RESEND_FROM_EMAIL: AgC+3F0DdKIaRLTrvh62gHkK667ZLdvkFyS3TTw/tvLVSnLvlAKR2WnqhijnOCP4UPy8u2TcOKxnANGzaT/OEaYQtJtJYSf1ejjvKDUwTzeFcY0xoBBK8u00Ybuj6pfXPoPPt92Www+OgM9sqBJE8dl7/QvIS7MY+WX3ZeL6U7POQnrxlK76HfRiwPkrd/F98MuKVh3nAYqVrJrmClGFbBaf6VgHpznWcrFarKasGnwwcuq9/1xqwu9YSJyutxfKfeOLtY3Rjp0KKRGdvimPpZRfWyJOAKEgo6W30M4Duqw7uEmHOhAOPYaFExTt8pbPgaXMYSuxuCCtD/EVyFGUBvt/SDL85p8hdtAybndQNJwdoUfDZTFZ2w81fxyheCWXcyW7Tnbs6NP5yIKYdD3HD2Q240/0CSWcJpJRYCWQPnk6VE04ICJFDq+BvuA+aHSXPoeM2jZygi4LpCVYQWoZUoVXY7tSm/IED80CqVhN9dVJzzDAFSLFMcL2W7ID4kENu1f3NtvlACKw/+2dGwuRCz5ZAZ1W4drtIxlhDPjP3CZVhymaCgOYwkfxn8TT9Hzj6eUcqa+8WUg8EkTmflnU27qKRe5peMAv/i7QFUtnJcBuFGORW4mZDqV1uf8S4C2tYWe3byGCi4jMSZoLZqNYZEx/NcOlJch8SDJXU7lBjtGYFLcsE2HyaMuk5B+W7Cxepd5VncW5SLQal+4qTMJ/yv8v8nyayX8AeEXiNzIAQaB9I6zq
  template:
    metadata:
      name: resend-credentials
      namespace: dev
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: dev
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgAvlOR2HzzG5W+Fhhgr+n3KV1gO3EkfZJ3Qf+cfffrRd7uP2wzoCWVolfr44h0On3CuR9E8vYAzrXJSLhLU5VeopgLsviVQ3V4v9DWtcKKnrM/pOLYp3vsGxout+U5nQGAfX0A2e0D2qjNWehtA0XK7z1f4L+Ck+Cw4LIZ+7IavGaegmf1jRtkvMLbaXVoQ5cN4Hq6htRm54mlNfWw8XGsrDSRyYQta6ONqhDxkYlZe5MH39EFXb/aR+8wt9cH+kjOtGxCl3A28Er3uDdxzRd0gzolEHQy4sLlMskjIUGeiTwKwL/xTZpjFzPY8CQeulE9DvklCY6l/dTNFq9wMWh5jKDS2+84gd2U5F93XJE7oWWL4kee4ymhs0RuIptpn1FIEDzCpgkmQU8j4adiZYg4bfa2TSPxolnZH4J2cl1sl6PUgYmu7DitUyJQ8GiB1Fcx4FFU/0I00kzVW38Th077xa9PwWogtZHH2fqLWA9HJ4shEAvWu2oWe1RVaejBzZU8A+9FajwzbhuK3ZkBQCS6jDBNVgrllWkA+XHBNm8+88OXU0/LCdB/2GN6vrfNd/72V+43WLd0rHemZsDh+1KkJ862IGOe52obz7oy0zQgVbhFn4R8WJpzPX/IINv1whTeLKEngTBOhce4Rd2MyHQDkDtbDU8sA8o10Cga6b5QVEnS/RNDlTu6wJVXasjdPrdosTvYLiF0bKHQn56UUem2r9hgPTPNCuHm3aKtgfd1Skzq2Iue+
    MINIO_ROOT_USER: AgBTr/qXig1J6LbKNNtQaZQCGBRWk72gKR2vjfVgFX8jVBAJtqkettHi60s92Go+BY4q0fFCfmeEJFgBQiJZ1CDMsVfYwwDarEKvKoeIn120lpDhEQzX9ybIaP8ksEZ1lU/1lGF5k0brFOn1as92QjnWo0+u+49qA7jVVaZ3VuYxKtE1Kvr0Zgo/8zQsICdH6KMTL5mbHSIgceP61kZ0sR56fMSY+VOk6oJUMcqLdvgtFTmuvUpUM4+H1ipAxzkygAFL/PId2TLWG7DgpvMDfnZNks7QiZBJuyUzx+7sSJ32/LLLDRnrMdcjsKslaNn/exQY5QKfzqcQjMu3kZkOtP7SxWQGTL0+fY34VBqGlsr4vTlAEbD/JUIr56olObHfe7u/GPyWJO4XZqctRxIRi/GcSzjtKTuE7a8QzIS9xFSVs/QDfl1dH+Uc74mAdq+xL6v7najrPzhJk88EKqBHYFJiIWzhuDuXRVrZHnp3PIAuxFjAQ48Yr32f41LV4XWlga115zmMRSbr/SiOoutE8Egf5clbHhmyUdIeJDTP6GO6pk1sUK/rOrSCLtuqKwNuYNv8dLUFtT0ShY5OGUv68zC+8INLIAZctTIcsyvwtcllmaKQqG/RDGuTXrZxFo4wwyUgzYMiLu5u/kCOnN1Fp9rXVkBoMBBN+touW8CQ7ffxF/LO5G1GDsVvUXQonCDFGOA+Sk5IlD7CrE9UDnkvX0nVOQ==
  template:
    metadata:
      name: minio-credentials
      namespace: dev
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: dev
spec:
  encryptedData:
    .dockerconfigjson: AgDOnLs5LVPQ10R2YPY7ay3qz8QLdJ9S0C8IX9Ds/yYRjEK7ZFh85ckb25H1MRcVwALKPGSAvQ+BS80zXHSPC32ZviY7C+ivwC8niH1FidZ1sTXJV0t9WNpQBD2aiNo9T1M4PReOWfaSyuXw3dqF9tOB15zkhMfzymd/qTx6OfUOx0j/Bb5R8Sk4yLeIoidD6B4rax8hadhrHBTDSQgBbQ6eX5O3YrqvzU425Tr1lauTXdhMHbh2dURPZmZUinhXtAEAa2rGnIoFutJCVypFUt/8reLG1AlaTGXBrAhibOagHvizAk2VcKMmglpB3Y973fDBTze5mLPbyRr9VzIUe4fnaT8J9sWIaBQL+r23/K7WQXTIxYHV4d9RAwEXeVPZuO1OB+kqEz40cyGXVTlEl97Rp/7u/k7SbPOAYO9uF/EaZBS+tYdndrp/AUY0R4oy3uyNzBmzqwnd7Kq6fj4wxZcG549eLciDcUe7DFP31dnJO+H5AYz6wqitYr1J8Jb1yC/daagOxsZdlTe4OZ3/Lgk/myh7vGLbMrtaw6zshMibri7lzyYlso+iXnMXQh81JTizu42PM+StUBukZZlANIX0iG7LhbThlYQVdW6vZw84K/sq0Qao+WKxsQZfXCosrtuSz3FATqwnGImeA9/pUcOiLxPRRxUt9oktGoc4o5lnI3y3fT8yQg7PGjeOSkCtj0A7HTq76+d/jdpqD1XQfLJhj/nQaDkgsjbDUleIEHeoN0fc4d0GzIBPjWRgqazsv+oKLfrhoPi4S2JmI6/HSX+AXkaU1CJ88pSzWxi9abOZtTNaYjgp6dVBARR7rN82/vSMaZ0CAtnbqxcBAITbmD/TJUH/o4r/ZiA3Rh1BfBXL/YcRJLwDw/sXXr68stJzpUWPRvuMGsU5DJVhxt8dEFG9xqq5F6BkrP8L6N5gCXOSka/E4bcI9ItNeUB1jojE7vcmWxcaRirMc1J7OX8yt3yMoAMDlTkT
  template:
    metadata:
      name: ghcr-secret
      namespace: dev
    type: kubernetes.io/dockerconfigjson
