---
# ============================================================
# SEALED SECRETS — DEV
# Généré automatiquement par scripts/seal-secrets.sh
# Ce fichier peut être commité dans GitHub en toute sécurité.
# ============================================================
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secrets
  namespace: dev
spec:
  encryptedData:
    SECRET_KEY: AgCxSWUehvMS597I1YWS1UCGnbDMAyb/T1PaF7MzDhmAf6OeJiYtklfusSxwbiz2O4dlbPJqoaEJj6ZZavhwOEx90S0qCc0n5pbfi9ggwUDl7mTefkLDBEPlZfx2koyY/ngeaZblwtdgcaPlaQF66dPxUalWwxKVnfe7wwtY3O/91Hne6qpvLKzqxf/etnyuPhMwY7fmCtzcjZXcx5KzHHnYdmvxtSXN1qE0cBUpZxHj7dgbwiIHObDoJPkNeignz2PicsM41JY90zcIkdNNW5MZdYjCMThe/z6EGa7LrqGLHcAFMSCCW7GqjDZ/WzMHKEqFZbuPCJ74QYtZdKBRUTXYFMGSGogij4aJdHTbVbGWOKDdQxOEwlIaiyN/BEA4r6tqWaH/wms5DyBr3HnCD4f3c0VSlimTZJmCxs516snGOLUMUL8voJW4PDIjUnVkuWXCXaJERRPE31wEYWBrOkPwLMeDPMJ0KqMxTcvF3gfT2sCXbjbqo+3CLHpAg1cKfYCHlAQmUO6AKAzqYomhXepLb2kjr3+DJsD0+nDn/Ykat64NYR2o1JApBBuotWJ76ZmEjtFTo68pSNQpfJhv1R9ltYuixElcIQf6Otfyzo4mSG3JrPxzcCj6yDH+Y2MXo526pUYPjFFGojs2m+GL7ZZPnlHZ/6WXhpFCXtfNbR1sTv69Dvf7RRO1XNSw1wEOATNnMGlwpDY9iEsLQ5ufOI7ziZGRuUuPiC9ZDcH6pPjm+fKHi8dpug/2OJM=
  template:
    metadata:
      name: app-secrets
      namespace: dev
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-credentials
  namespace: dev
spec:
  encryptedData:
    POSTGRES_DB: AgDBUlrT2Qd4Hf/Eu2gAbuQDvMzpURFA3P+jv0dppflLNjE8VTUJDgpzqwlejNaEoz7DXeaMhFiur/fFmjpxwfKyx3l/2ad+se+JP91ISb690RrDTDQIc8oaOfS8ZQD0fVzIvK+zDkGxOCN057/7Yo2jpRdLaW7Na/hjWgv8WCeGIQIoAPw1ufMWQnLwso4rW09gesDdhrdmJ+qhuzqxoYoCp/ggHukYGu3iwXfHHiDGMI0C0tt3219DUfbevz0CvSQIjS+/isQHhOs884veHyTJmU+a0tm9jtzxBFHNGjmkZcj9YnrRuFCqZ8FeMT2zOITseQGWXU8vH28SQO83uy1TUcDo/TnXsBFPbO7KgydC1ZcFVu24THRxXcWlTqZMgu1fMy2P/Lpn9AxbEWyYo+x6hCUrDPrtlOeHjtvGUNCH2ePb4nZJLhsKzBFWdcfp0NpJB3UYb54xaVHvOLoxYmn8q4mROWwXARyWvaS2hmBFxMLGxGJvdnqnEac7Uyj3zJja6sv8QRR5NBhysphywZTvoYhWnK9g1Btw7W9GwEFAzc2bs9to7nGYEMpyhokQFe9cxf3f/mgSU4cwK3URcCDCeytuCXdxkU04xIZZ6MeXfBnn+GY7Zt+q+QIMldkUNBTV5+yjM8/CkMgrTVpMOsf4KIoic9yI/F4O+PiGuk0LWWSXmZmfYVvbAL7HDqy0slGuCCYsIQ==
    POSTGRES_PASSWORD: AgC6vrAaw7mRPiHhG4I/jV77gDiWKsoNTSqVC1TZ0aKVirBEGaRHT+aaP7IFOkDhy+HhZmaQUFuIDGY64X+qhjJJBkJVgbF5r8IEguILhEl7loY+WrhdqUNh5dMYFxbMTgLm0N9CvmyaeOVvWJj0PqTL2hJW//6AGTIDdcK9bgNktUSG4ayO3ystFaEV7wCRHptOOKbb92icgoG+bZiuuW5yzEF/igEMb/lG4PiEtiGiQD+aTvdAUol71GcWFiZZrgLfWahfBxeYkAwTEVVLynt7aGD5QWCvIiOTHI2crHeilSFKcll/2NWos4tXbGU8KHeV4TwY9lt0p3tmjzaidYPY6dVlSW9Lrm/I+0jR+P0Z0MAFDPq5daSO2GyiDqLi5kP79Dbb54B4c/HboPDxzLI48/9QbZ0WuE2iTm0DrVUYcgsSwf83EmkHBMw9CD1mI5PT9Cm/FdN99aMbBirwwVk9J6kvI5hyx6xdze9EL7qKjjMm1IBuXIWAGo5mAyrdzI3VkRWboMbIakvMF5irv+d0gfZ61v98Qvjk3UycCWvZCIP1REIDowjQ7ttnODeYUI6REx+qh0ozbgPrAygVCAtnvZYoda3EycqM552IwvNogbczI/lvqiyEnmoG2FuPYHcEaFNsgqGnu5dOh4mCs9Pm+qr7qyPYQASTPYOp6AfLn3VYEZN6mo3NnopJA+uThi/rRkkAs68tyr4KdQUXdfPgq/q/oQoKQHv/1eveTYpSBCZBihEcMWaREaZ+Ug==
    POSTGRES_USER: AgBA2m18kMqt5K7FPOGqCOXyTPm54NYHb2BPNgCtZGnrrCsnpbE/IIQyFa7TZHrtAswrgpAsvXncefBc7vnoH9S+pDXrgIvr5y/cBlbS20B0gUyaKJokBn/fPBatSKFKLOJlOZt/LiYQ4heSqjESzt7HSaMk2RSUZOTrEGfZdlZrSsaDXvZ0o4eCAzIY+gXFvkeOrJmKRELsWdQ7tQc9I4nyNLEtC+i7vdpI5CyZ2LwICqmWpv/DGGlCCeQevFUJ3sm+s6YRbe45o8TuCzpY4hFd28SCxeuFvuW8pbccOAIS7cT/OZ1ibl766Ewlq7+ygLiLo/cBT3vQZ57cpkWht9LhNUf700VCGi+QcjZGoLlyoQPPrfhrjMWAJZWoxe7qEizTQ7ASmEoi4qdawjl5oqD2LfrISE6vEXRSsPKi9BiLA1HbTRStMTZlsvnJAalDie1sw83JhjNEhgj9CZD+PKXUgfRMk7YpNaYvaTUxt6fFlt+YzEeInare8pfQFD5Ezh7g3pvZYF3m0a/cXi+fB1UvsAm+RPJ19o207Tt+TrkTVtUs9YUB9NqmnTp7NVHJHZcAIZkHtnoquNsQAO70zWK6fWNqAv9ZJJD0Ep7bXn5qsn7SrZeQBLtoojc+SfrWcBNseui4MvnTGPVVyL8w+KutxIT7uxqZMvyqGW3KsdJVPnwQB/GFIGU9xtXvsvXHBbKxcYPOHrofy56g
  template:
    metadata:
      name: db-credentials
      namespace: dev
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-credentials
  namespace: dev
spec:
  encryptedData:
    REDIS_PASSWORD: AgAmgesBANdPt/FBOu0Gpmw/RCSKipx8hRXt4pwiUoJA1Y0T5ix+V+SBMKJ66W1U2LUJsWWMWLEM9O0Kx26YW6ZiZMu5TxBSqcXrHjCXwcSQc2s2sw+5V5pOLpZPZxr8YXRJx1rRmNdlxC9WOr6RBZtI+y/jntquqUj9UirmtC2FRe7+2US7h5co4JWM7cfwscCE41S/CXf1Ds3lBrsV8bHUcIuh74fwdsPp09jUgSGEXwhmOa4wnOw+ADoXoe9xqKDcHsFzZkoFzgowlMImA+uSK+dtaCr+Mn+5aBTWCxYb4kjuh25wMZFu1Zlk9CHMmpZadJ78i8nkGGYUtTfYVrr9rKLioYYFE2vjBm1KkPCbqxViiA5tWTAdlcxm0vCyzqrtoiSY5LYPzR2oLDmfBiTcJvd6UE2mfRrq1Jy2HYHWALTv6KV0efhDZEfMl4LujAz1UibKsd5AFVZe2vVC5HxSC5CEe5ZtulvLPMtYWlHoaBunT90omNzNCc6Ivf5ISVRYrfNl6GD6xEvNDazdufCS2S4n2slIZyNG8hvaM7VFKyKSaj7su2lpUVZNxcd1DHLIGZMHbCtkKP/beTqquzsPK5j5b2LlutjU9ejEe9+0bzXOwYhilXgJiNhCWbBqAgdlYEOuDK4pTFEQF3EbwQ7Y702r3tHjTsjO92ob4bx2+QPRwzhmCkaVDHkpfWK/ik8oR6aGbJkVqR2x9pqKJmdLqYlH+WTotYM=
  template:
    metadata:
      name: redis-credentials
      namespace: dev
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: resend-credentials
  namespace: dev
spec:
  encryptedData:
    RESEND_API_KEY: AgBs+mZKCiGDShX2ZR9Bvj4EcUfIW6yjtMXusWWFn5GxgfLHkKxA9KTy+n5SAmEGBlSwdWDjxFC7WqPlhODzI7C9geftniMt8i5UAfs+sol91G8vponAQeNwgKOhwmzl+65ECClDOcTErvxxeS3WYOJ65slLlbZzlAFq6oflyfSuUVSoYaGxhv2VQDrmfExMGgP+K4c/lmzpwGUY6zJ9ujt5p6QMfyyJ2zoRNri9hTZCbIyA6NW0RaJBn5k2rl6uWX4H2foaLUCg8eTuIAvj9+oQSZbw4qNwSyS17x5BlgY5L3jHJpIY4qrawMTQc7v76/Qon8VVqbVupeHE+ceqaknzhhHXI4PKwePO0l9bkgU9NBTcX2sfqC9vpT4Xp7INykcoPlx8Qe5jZbZP0ka9GGb9s/54SF/D0xjUHl/NpSxnmR+5wor/Usz0U74b9fCMU8ht0zW9WQIBV73SsRNd4775A+EOgRzqPyvc3NYs0IAiH4PJ+UX2cUiTCIodqcpQZEFO+zObdJ3rUjZre47RikESZaKtBkZJyXeWrDVIMLvhqN2NOHi8Gxbvjnkua0AOXer0Z1AYZGTFCSTuWJhGavtRqACdJ/1TM1LOYIeQlIVtxj1hL/1mkc+eHPfpVHGqUbbunvSFBQH4WBlU1VMDaoKihXmfwcLOnPYNsUnjV5rsQrupaY2abz/eFQs0Pf5/XUzYNr+FXbQayYsWrT7Hf14yOEf1kdjCjonxIKqnKJg58xMNooA=
    RESEND_FROM_EMAIL: AgA/32VpFP3PqBg/jVf6ouGbDNPX0rXRg4ihMT2DkYh8qMHopGMnISplIGkrmB6poM1tq7B9Dr32bahuM1+Zm5qrb1Q0gIhc6qHkyJxYMK8tPrmPDWHEYEYImA+WtJzRU2LzEho2YYNfu9A/njE2UFtPoJHIjtTCsRfo7qQwJFfaKqzaPHRp7iSm3WY/gpv90wt7PtFuA7HPqK80qtWBRyFFQOdRLU1f0Q8urEvjTbxBCtxlRzGkeG8GkKVx9IMcNEB91s/wanUrIdkp/jTLISSRCWQbibXk+JNBtUdjKqzhARkxFTYiDcSFSfWt0ZsxeDhGaZPJybvXBVz8a8KEpDmyDS88gX2BFAxge8gmgcqCTXZ7e58A3U6fbuzWjatWvvqYyrpUeoZXrLZVlZfdx+Ls/bbau+81IWea5nih8gfj5v1JY/p6++BrB59582VM4XystpmNuECP1joGjMZsq8ow8ddNqAW4IU2THxteW3PorIo/MRC2McI8k6XYivLrrMek3T3JyS4u6xAuUe51QzmAv7dd/Qau0VtHtAuz0mKYPcjZfVA0Vrvdg1sFf4z8SY449uW1koZjck6uHYge4A2zNRL4ABofOh1G64KyBm9Eq6m4Wmz1wg2PD39DWWgExXukGp9UwetZSr4zdT9DgABdRgErjBibrSjtNkBRW14SrNkLus0Do9kulpZyp29KaR2ZB1X2KkblGVN7T+IumjuzVykb8GOiXv3jz6DtGVZr9lm5
  template:
    metadata:
      name: resend-credentials
      namespace: dev
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: dev
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgCSRpzKNgYBTjyS45nOCHcqtLTAlfzUA95f6PIjX97WeU/ykktc6gJk6FWooKEnJZ16X2BnvJxqbITsvMfo7sxzqzlw8mu7FrZuMAc+pdwYjMaUF5nxlVTdMkRPCJiL5vc0MNbuWM3omBjANXzJ0MqxkJHYeuUudL+7Qy9At1cy16Wl0cGaxIIYekfOcq09ZxESLe9pqhPiqNgG5a+3kHGkONnugZ4HuZnuvIwtkvemQuKqPhEuZ99e6GebmIgxVIx59QwYX8Ma6esHTbFFkIWk1PVDdVGGznvo26CxPjRwpZWj2KFdKdJZRC+FuBmkTtcE9ntTaHsPsD2LUZ27DjwdlqihZ6ihdtNh3bptMFEbmNzu2Y3DkuOqJ6ckRvbO5f3b7spLRnanQKB002IVZSFU8cHrE7V7asd9B4o0QwRLsdVginQAmc72tkkS9/McpjYzcw/Ub+9C+Ug+a8xYmUOHqnoXcits7eb3Y8C7RnZyslJ2EORlvHRSGA33MpnqgTN5rTN22TklxXHMB7zw+6yW7KgyOb6q+PtWhmGGw8eeooMBjH4Bv0q/3417GMXm3D2N12DXBQ88WLB2oBOPRsgFpdDtzKu6nPc6PzB/pfDBwJy5NKF/wUs77mch8mIb14dHShNTlvKPdhmBnWJW/4Yv/ztuVeQc7I312mbMcWyeJFde/vBsObsONR7vJxbxiewX33wqEB88ZQ5xsXrpF65D4u0P+GhoTwAp76MT+FxuQZTUNFTp
    MINIO_ROOT_USER: AgCNd7N5iV/HM97nJ/Tj3tl7FWucRjGSy4xNljoBCUvDi4KegBV+W7wtLkIHqSeEQlsoJz3GJE6oRzRZvC2xEvzYv1x311DqQTTIeBgPenbXx84RF72RjESivScqdOIgeM4mu9nktSmv8Jgd0EKA84FKPRz+CfYfIqFi92cPXrd7SGO4EfrGjPx5q8DhuZXTTyt9W1Hh5LYk4rrQNRP2WJmqgCf101RJxcAiIb0GWNGz1hDexSTlBV7b6LyH5iHEYo4CAcnxbP1FxYGkkHo70j7vOq4BivpXsWatF4AUQgxeKrEQXHeZPrwpUdwmzyiAVnYOiuliT5A/k5miP+NNTY+n23B41IR0HIdJtH5MQ5slKzXFpDhMtbfEWgJHlRQAnPgdQNAFjjqbld77GaY6PphvG+Uuqx2k4HgffylGQn1zMEmMDGENdWI90XhEPy9U4HKweAsw0LgV+1QBAcVl/Y25daTFDKu6dcsDEKtd6YBVzu5zDu0wM625hmnea9jdKYLSxU05pJy2SW2QVn6lnCEhxDmNYyxIAhZh/M38+oIDkZbA2qniy8ufeh6XX5D/jy+ZkYG7tbggYijtfPj7hFX3TOVsCpW38HHZjkuhKBF265PXjhY9qNLXEkV7fW0J45KWLi0YMkkWb33g/v3GiuCUyFWPtHoyHFHMFbXeJ78//kGC6gpioUE1dybHaLcIZvKSXSUP8WXEL/GKAVqzAG89dw==
  template:
    metadata:
      name: minio-credentials
      namespace: dev
    type: Opaque
