---
# ============================================================
# SEALED SECRETS — PRODUCTION
# Généré automatiquement par scripts/seal-secrets.sh
# Ce fichier peut être commité dans GitHub en toute sécurité.
# ============================================================
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secrets
  namespace: production
spec:
  encryptedData:
    SECRET_KEY: AgDF16YVxQ2JhZ6eutzBDoL0ytPwd/4HKlMJTatqmfRgDt2FfSu10MFuQiKPIR6fnTs6j2Aluk0MTxMEuIuBx3FyCy6YW7vH3tS0kW63D03XyzKXRYdG6YpQEd/06ZZk5rOFpKMfx5tg144+FR8llH8Q8DC1x5o9fWPXYKCTs9jDQ2OnS4fS+I1BA9v4PoEeGq2HX4HnwMT4UU24OLYUVAAE0ffpBVnXd8CFC3G3rMWPaw4Qy7SJ6FzTOiO7sLEgUtjka7Oxj4wukh5JOaNmwlX7yNDmuOig8gj4ykU6d0TJxsNNyB9EPH/FR1/+QBJ5xfbH5izoyiM5mhwh8y5zx1bupFeGNNj5jTtFxWt8Td2KlA//s7SuUU+ZIBjNUEnj5aXW9zcqiOFGZ61e4/42wPOwjTNrDAUpyWG/17D6H0mydevFlxwRY4eRwjuyVtk+1/l2fJ4SNlub9vGYgAHQaXEqdrySUzKKjUni23mcMnyJLnqAkXL/n84NIe/pD0Nvmc2e731rWdeSwgYDX8PQgjYleqpyVPP5VR6eIMdqWCN1bq1r3s/LQ3kubN/WFj0xZAuRWRa0kGiiwSUcDZvJCVoWrpZwtIcQ6wcGr3g92hx+rNPabLTPF/qw2cIaIgvL9FMEfXNAxpaWcVaO4V0KvrBxJbm6M87C45gb6xJp5cISFI5qfrGOIHA9OeoSECqINtfpuac1hxXZ9Fef7Hr6uoXzq2URssUNsy+k383eAFDISxEFw83UrwCVCd5PQ745lq2p
  template:
    metadata:
      name: app-secrets
      namespace: production
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-credentials
  namespace: production
spec:
  encryptedData:
    POSTGRES_DB: AgCEjS+PqTsJxAdxMF6vuRa6wMtuN+djoE9zI4PdgiAv+9mBCLf274jzvXUdHR8qirvr9pBRZ2InZrysDWE7huAlgrzk1ly6Ldmg5x488GHFsUuZrqRTxYPoV0qBNugDlJNGNUJJn87oyYovUTrnrxIeKlEuUYmMjlKpsEticUw8+/Cs2VkE5klyFGiPpjjojns+P4iTnbllWjVIaReZpFmyzexu07BcxZboIacNSVFsok+fSADYo5AP0WkqQuLs+fNEeB60zLOw51KnVtlgRkRf1uL594PgDp8SXHFcVPdcndCVUzLW7OfzldylGLvDhy5oBcWZ4TBqLR9rXBL1cM9DemlhPQ2IyQ110R7e2d5ZNnxxHjs0ya+sRV7au2AlNUoYRUIGu6dkiDR/RLkqX2bx+QxiQbP83DjG/csrWsKMCrzMdpkGiZPSG1KA6NfIuc4SISZXtrcJUcG9kgFIaPAVwhUO0bbRZ57QaZjWcO9k/+OsexOBaGVe6/ZYgiNUuNwgBkt18TuLkhV8I/PuCc5asxbDZbRfxBemh89Jjq90tzQt1WNY/SAX3iAx8Ndbotev/aZh/reB4ziDN2PVLIPTjex3PYjH6nKSFpFKNDbNxqkBRA0Z0c+TY/Od/0VjUFQ6UnoNzz9pO5pxw/0/FcYmPSwN59r8S17+KwoMO8TPS4egJhSWzrbxjlOSESBaFo8pDxTVrQ==
    POSTGRES_PASSWORD: AgAQ1b6lcaCIkmQfpKdUR6ikdAP2V727zr6GCgOCWeBKrmEjFQgsIbShp6atxCGPT/ePodgVlMe9RoJLyAyjkDqkonPFEVkZJdmBzFAHQbJUsQ6n8Q+SBs52f0HjkqPGsZiiR3jF0WLOLIUFIUYxtASJnCN1NPppJsW5LcHGsO9LkeaZQ0SJqLr/WZZCoPNrmEBgbfB/Ie4YT9EuPHeYDI9sGldPKp1xqJqz/+D7y3eDcN06snyYZTRO5gOUp+RulCaE3VKGDxDimbOKO5ZWFvT29+RNXh4y2r9iTvwmem+EGaUPFVLhLp+Ohp76956jj+QAd2kgsjdi6l7vf32gpnDQKN99RbbvRUokjchpMU7sAOi/HuC9zGGykwEv037p35Cp92FEh3NLiVF9gbHx4Pqz2v9zhsJUupyKDhN30ARapsHnbqcbom4kWy8WwuoIt2+2o7+L4vV16iu8vyMrzyDAOC7wOaB/nrhhWGMfqSmy+a0hrA6Rf87tob7NbC5JgfeRn7YF85IbGJYMwdlEuoLNvIFvSYivrM4e/3agEOnzPKjOoch8MmsWBUhQYwXgchYyuulq/NFQfRhypb9Oi4cpQZfcyG8IVP1DLTEk+zkCUVCoutVDhOvUU+us/9k19T1Bk6sF23KWKJf6zDq/P/34pxop3hKd2u6QZ3HVT3vDOYkJHjEmdmE0Rt3JOIj9UAr1GIGzGXEaKPWC/g0xXyNDZAo+2L34Ghx4/8HlbYQ0TrxygJjDUbb33ZDUrQ==
    POSTGRES_USER: AgCQQpgI3i2sW7YXKuIHGhpuE8MTJUEWS94vWNLGEmH20I+nMvRutyJeV5amlij3i1Ww9ikWwBqIAA4sOzMOANLS9KX9Xb2wwmbsTYHLyjjsDbOgcKWsgNW5oLQ4QSX8fSpb8j5Io/bWA4o8fRZDM1gDrmYnPqrbhyu5/KZwr7DEmP6Or7Hsz4bRdupLYplUbCCGEoy/ZhzCuz9b1K+5AmSbWKAwr+Ku9t/AVh6I0ljQ35dslEpSCuRgh6SSjUXkQdTiMJzzZ42Jn+TSHTKFdCSYbH+lfosOOakZLY2bKoulBS//ZaLm/BdGquYiGW5UoUvLJsBxhBNJpVnKcXb8TKDILtmZcujtsdhDH5tgVGUAbwOKJkyErFVUf+9ABx9f2cJxM67yw3uPWsYsoTL4pCEri5rfnBmGKbJ/+NtgohjialiE6lKm5OpMDStqoWBmhV4HhdJnyfXUuOb2QUOscCpcH8zmzG557Dsy5OYbzmh+Iuz3eQdPKKHZis9rPG6FteyU9cLa1lV9SVqRhRoxBGwhojCQqC8Tvfmm8AbsPuPi+cXWGJte4HPScCU7jopZYK7h0sCrLALyeh9rLh9/I7KSgkfct0R22M6KU5+EGihYQiNpu+wOGTLINeYgEzVaixxMFdpvyBWp4559yATDHYprAhsT8L7jpgLDmzFC8jrDc9KFJzFInPUXrapVeoGfsKmIfhVGyKLBw5b9
  template:
    metadata:
      name: db-credentials
      namespace: production
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-credentials
  namespace: production
spec:
  encryptedData:
    REDIS_PASSWORD: AgDOviMxjzZp4czvvMh7kgk24cFAak5jb4NGeVH4rNm8U9L7+Cw3K4ekscwOWW5U46+dXjhRNcanhc3xkq9WJo0h+iAN5F9EUm2EyY2cmB46FnCbchMh2Ec3VN4By1ds6FZmmXTh+tmWO/+/tWjM1eLMH2uLUYptJD0VNHLE4M/sRGiiDI4Se/D4ssGj2D84LJC3icN4PY+f+3A3eiwnmqFaPzREp89KNy7yHITiFlkz4JAbuMMa//NreORKuqsSPR5Bu4xXfDT6mh+Fo0fBld1ztNbSVTi5WHl5Bc1G4ZjF8Qqj7LQqdJuhxjVYqeBxfIAQFvi3EB4n8ahDZvRWtXpcu7EV/aL/miqk4dCtzWlKT4ZJeI+gStH4WUcgajh2pSvRi5Ht6GBEh42uBtlhYMmdZpRkk7OyHy+3BqTgDcXZqISJXhxKWMMkhMOYV1u/vnBJFZRzWVE6BJS/Dh7HnxT5OUWInrJIOl7M9YoBMAsqUeZyx6Iiv2BHIHme5irKh9EY53jJ+h4RASVkuYNdlBUk1COEtB300BVePVpUx4qtHSGwLhNMDaJmVx8XDM6+Q5jVsGIw1hy/e9qER1ok1q2hTE2HPbAdAFpZJiJQh+1477qWUNfsRihBJdC5fK+rUsanUDMM60uILLvO+QDzJ99Uk4/0golffjSlysxhW9zDCYlD6kJx8gkJLWFV55yZ/aBQ1Z2QkDzzNOZgIq8BIR63r5+S8cRL7EU=
  template:
    metadata:
      name: redis-credentials
      namespace: production
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: resend-credentials
  namespace: production
spec:
  encryptedData:
    RESEND_API_KEY: AgCQCwgDwCmdzAkCpQm33/1GwVieBv+ROnUYxWUuU2JCN1NUexaLGOcQ4Pj2Qg+5ep7NzJPZvQ6AyJ5g0OuojgcKN+IyecDTX3+cp+BgC3UaNHphMZXouspZRwKIg8Stsdrr/1jErhmLNp6q8I4flDPAqWq+9mK4eqwf6YVIzv+GMvol7bIiN9wkAjZqZoJZkG6ZrvgQixKqpbBCG4QUYrtNscEPlXAtaON7bzMJuLtyUJZPKpvjaUHf9XbUiwiO1OJpdhq1Rtq7Ycjmbezp41F7nXNH59TmhbDrR0ncQV7PCWhl+RnDUMqHSxpa32HRaxBWBIE2ePLrQSuQjq4WyobWlTzuOxQYoR4mGWcBh2ycwWiSr7Rfp75Mcyr8isBemEaLRK7qUxIzHnz6jq7QXcvBDkMCvdtjXqiRRBYxzE2dCsISssSdfIjQkpyGj7IGIh0o9vSVLwLKueTJRgJBcTtf2ovH5+JCsjEmgXQEGJSynAdhNOWoQklAD4GZ7/aBuOM/oyTs0H8ZUaJWGJfrOQ5kLwSBb9mTQAbCn8taHiR4Vg9qy1LH4OIObyx0t4j6ZK899IhZVnPp0hqROfamcXMaeUwvr79kd+vBpjgeqj4YVVxP+vB6Y0gb+rdvVQI5U6GoByZFGohm5vq/YRQbHMjCeSQPeo77+99vtx/x0RAbYT+3F7ta4o3OEB/H/a1LUKelvA+S7GTNVpLN77VEnxUv6F7QRaRTfedz2gQxnVV7bp8sx84=
    RESEND_FROM_EMAIL: AgA+HOxRf/FmDsNvitoVVN9X2o7iWW53AZ7fbEinZduu1nw02kMG+rl87dncHRwPJ/Y5x0BDIngE6RvxIjRGrksSYRdeOJPyq8MBE2uGPN7A40sxfEqRyH4pb7PMEZ3Y+XV8EtO/Dlb8xUxFphzHoWeKE0FWllagmmK1905L7utBQPYZ1QcMzMAbCH3zsJ2+vHIHgUUIEmYO+z02XSSm5VM/b4LjXnROF3QLR+sSIoCbZ0m8zpTIRJDDcP/dfwiD/2dUikERDsa9xT5gNobTg6dAHN4YLSbsxVGAVqxm6BQytjtV073PpnxoWyFDuyhtrvFUnZrfsUgiBhAi05FSvm00m40c5PFf0ytSoUoaZj1aPuOGFa42QsXb1Kj/08rYQzgahjYO+6tBFgjLVTe0X1Gin7+TtMbzm/b6QBUpvj8Dw2BYXmP33LL4dkE412ZL76OYDafZxcFsIvEv5AkU8uDjp7XcM9z+vIt/8vdEjNRuCPAO7sxUdDzGoulo18wZxeU/xE3IPyKKjp676IyFv0JXJ4ZEkbo8vJ1v3TkyWG/IGisXGr1RRjCiAC1Wc6jIWeZImYgnpuEzlzsmwXQ3EE7/i2ZTPBkcChFmlMvE9Gf/g8PraqL2JlmdqpCf6v8HOHBIY4DtjueLpKclBW5YrQcAnawSGMMWH7l9Al1WK0Q3R8yzdeuOFTOwCoqcGD5AzCnsodfTwqFmSUf7JF5DtCqELU2DHn8NpNRCm21lLNSLWfLG
  template:
    metadata:
      name: resend-credentials
      namespace: production
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: production
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgC8jRxuziN+4JkfkNGjsVZPubYG9juNS/lSLIhV/hPCoNMYio8C6+3VKFox+b10f99brsHdRyoyH4js/VYGb+ZEK70FKEHxF/HxPpQ5GKmebJkdDU4vyTOEooxtasiMirO7a9Qai1Lbfke0bWKWrKb1aAukBB8CHeENAXBlIJrk0XnyLEtnZrRgh49k2NQBUBauvVMh5don/y9SUoFeDyvQYg9en1iGeDuSv4Gj7KzRd5HX3EgTUA+0EVw3qUTd1RmZvtpeBx3KLx1jD8ftqXYC/+CUuj8XCnyXoQBTnT5yIWAAUbgg69ZkB47OMGqWHygkkzFo/Hz/t59PKDqSjQw5diqnUIvds0FvfJkKI94lWOPFIwl8O2Aew+cOFjVvvkJFJhWxug/Fg1XEX+8xulx1mD4qQQ7xD3YltnPNyElw+lMA4c62Eb3XoZf/YigTe/Ifu4UYWK2n/UwKfJh231Rk9AeYbDp4Aj8BG9SyXK918vfNooEPQaQ+mgFLVMCVleJw2IWKMtCEt0mms8QDO9J+4Bos8tnF+O4TbW2QWhcouz9pmkclh42mLj0M3OBbHerxqdR/Uotp5/HdTeelGKOXEof6hX4KWaHJYHw8SRgy+pjEtROC73JPDMdzfXLKhLP4yGw1OV3Azsn3ReAtPgBsh8Ad847ROfHS5nUp14nZ5Q53t/wMTd3g3Ve4a36JVAohr6WZ9jOOqzuSB8a6xRa1o70aMshaOo4+yyn9vDcOLz3oD6vz+suIrHitBA==
    MINIO_ROOT_USER: AgCguVspkkQV19ly1PB+clO9ufqlktOvdNxvNYEKA5XpIwjmNvQ361vMYyDyH3LQgRmIPvddiIbrs1+Hekpsfd3kTggeafbGzxULOiQUUHeuaN+dj7XwQlBiv0FvrsHYLiW6Cl7VwW/fw2TyVdQjQ15vGcnBcB6Dw1PUpXb1ePxGIlcIxHujJIXDhsmAQL5VTpGh/VZtgDRfKfqG8NJqDlE6mp5od1rLdKDmvc7RBHMcedfkR83iXXmJ3/ZEdGg1AMyCWpCpMMnLO+VOjZWrR6W0ZpNvRCWEVD2oNoFpiUYN3K8Vih2KjnyOUf5i5elHn9kuZqXrMPWmvj7SlhXQiyI4O6qc8sgUJOzAAFCoyV7hDUpXUQer///djSklssiTgmg/HZw5eCD0r3LgXzibixYzq8VHT5xOecIEglOY2PhY2WtjfV9VAOkZNNZv+K4BPP7CWFLJrcJlZo0PasUfi8TrVx2kTN2hf1q1GQQF+TqZWFPJIxIDRh1+QBvaJ5aBEF16PvSECGY6Iy801PY/eh0KoqLW/uGPM42RLT6+2b5e+Tykpxgwnc5iTjdFpzxZ2FnNJkRgWktFQDw+fMA9dfHc/BNKLgMLAxZOx9cFNCGX4LE2uX1VLxP6onwWRF5qmP4T7f6EGkafDhGksHzl52OImc6ez9GdyEZUIOeQYjPr5JPSWWS6i0eoirU8NYPCdvBn7PoFRx/ZH8AdzIO0sx2b4WX9+0acT2w=
  template:
    metadata:
      name: minio-credentials
      namespace: production
    type: Opaque
