---
# ============================================================
# SEALED SECRETS — PRODUCTION
# Généré automatiquement par scripts/seal-secrets.sh
# Ce fichier peut être commité dans GitHub en toute sécurité.
# ============================================================
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secrets
  namespace: production
spec:
  encryptedData:
    SECRET_KEY: AgCmoqurKmVOAU6vA/jUUTKh9UQAI9xoqVP/2YRgw+I8U/L5ZOB5k+JcSe74DN+VjL69ns/wHC5G28FfiQ/Axa5DyIIrqYBBY8HA+PhakGGAgmbrSmIUOciTOiky2B7oGVT/z9+LfcxWHqcpwC+G+S3Rn59NPNA7tI0QZX055SrV2OqSX8vCpsFs5T6S5d2ZrLdd5tOHYLjvTM+gL80H0QSQR90c7F5Ix7DCoS2wVwVx2CQDNCbVkGP19M+yw15H/OyC37aVV/OBOjCmTJ7C3FFMX+dLZxasKT7WD/R2HUPoVreev14OCdVyYkSxQASm9hd5cY+Vx5kXx2dL3wqT5/TmLAj50Y9NkvR0a4RRcEZtXgBGEsIk2N8UXIBe9yTjzqRVdgi+Z1zE6chYM1LgDlpB5B8i93MkWokHW/uq8bMskTsMncgb9xw4NZJo5kaCybryF8SclW86kYvPxGycM7UR+aEvvhgu3X1ymUvnHI9QotTD72DVAXxa39Vjkrc3/4yFDoXJDrG6gnvxBgQ3sr6Dx+9E2aBVBzMuMl8+VdreOVI5n9Vpib2VFiS6mwIbK/IB8hDmhMkAhUSJTlaRfO87313dQlLw/rQMSPezexVWQ7DAUGx+m6TDbEelzzWpp9TuX0ZISnbItuareAIf8QpQE+oryqmNdmZe08BzmRdOo0Q7o2JO4WGdb1Qo+yFj86d4nqgAnb+KBjQksYrZjXTOfOD0b/Dbk+qDKn3Cv0AyQWEE7evth2DwIptjLrHfN4ky
  template:
    metadata:
      name: app-secrets
      namespace: production
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-credentials
  namespace: production
spec:
  encryptedData:
    POSTGRES_DB: AgBf3UNoWMKmDkjA1bN6i3CttIpkUnIFmiP+ksP5Ha7dbRPSUdeSGHkJK2sHAglbNnFpPQYCWkFuXzYOqVTxD3XeDkDfLlsSkwDOeGBOuIOwQ/i7KPI3wgWcLlNHOwEEMb8/m0PMNmJTUnEBJr/Of2Wz20nX36NB3yCyD7HN/EFyv83KRU29T49fde0DhKaVDkSiDp0yKPrBDttDaxTnYSFtSByA6fLEPBYHKYhaBkCNa1B+xea5aCp51oiJ0zlx4tgzUpxf5r+mmKEZVYVhSEPfuCBBJVZN/uutxiKR2JBGhd0Irp+4VJqy49oHFg0mftvwAqqvt4PbHC8Y+vYsA+9LRh1rAaH4n/nwSvtmL/wFGDX6GIV36b+k3yGjqqtiiJRfS7nizlQSbJ7+URkxkD1mrLq0opV/nTbLd5+jgMONjzFKfuuObeCKeeFisAvpb7Hx9uvPL2OV/2O/gBMxlL5pxQffWYAGzo1+0AjDFvJ4yxEy76gtLX67hq64ni6qOqax6Tf7bbGytyOaEZnjQegoJT0gqD3VT4tCpdYXkccxMZpyUhp9aohu4hov8vpS880cV2pMN2u0G4OKawKD97Kyf78C8yq1G+6iLn00ucgHBqVR5i3LPfgdfI2K6+Vh0fPdd98j1LQTogKhfEe424Db/w3Lam1hEEKxW3IxcxBmh1RsaOHWgimbonVT8hvElDKuJ0amcA==
    POSTGRES_PASSWORD: AgDHKhe0m62aqogtfOTHN9UfpRgFUlTcXq/whHvImBvRBL2AiidH9jVvhQX93zMBTO3gn5NhdYlKIa/A6lUEXxHxzcGfOgidJ8qdgpcb+VDX3zuN9ZlAZidOQwyjW2g2bPevu49NEz4aXd4WChsgF3zCsQQicr9P/aiSBefhlaUWOOsz1yFMJImy4PiTm+jdXPTUCVDqAwQLHJKN8ParwgIHdcjAJY5evLniwTjdWNaADk9L4CURO8u8l8RazenIN2458s3K7gVXwey+GnRykCJlEfzQfHrvaqqsqHI6QQPrEPY3Qnm+Fncv5zPd3bwzVCFwKgHIV8UKWt4twkqSIBNNuEucRj0G9aZs5hXFkCVCvTmfs6dbvNeqErOy7yt27LeQjDNMsorZNMKs87RvVlTdlWM7Q67F5VvQgDA09/6ImYMRocDV1il9KY4gr2MqSOfmZd4cpsOOtNpQqrxCIkZiFOP0lPjYmcpHAdgVgwNeW6uORG2zzk18xqkeZrkGaPd80ZqdC102g6W7GSIe6kXZpGhi3e+AYwcQGZC0AuRJBGcBRaUYUwHG+aQ3ScSjD7zQi9Oi+I8y8Prj7+9POhER2NT3ws4DKKTnZl+xRsnxnl/sUN8voOCAyUC9VuOg9BhY/PMoW2AcWH3i3wY+NpTuT3B2qKeG/BqMxViENDPbm46FC8RxtQ3fSsUtxrVMzr5vRvGJwqcB87Gr0epEW9Q47KoWuEUIns2BkmPLBaHib4aID2Iv3ZePcDDDUg==
    POSTGRES_USER: AgB91B38RnxhXEP4vRNYW7fe3sESbk6SwMixz4BTQrcH3/XEhX3W6hHnai1eFjgyR1fNSns3lNsRnxpKzygiVMBcSMZSWijnSkGPuB9VDzUeSqsXhbYPrW0Ncdte40VoWKdb7/bhMY6fVxResZegx9lDBInCwSBP6W+UZHkR3hA176JxfbSDHmabaD3bKoV0vJb2eIUvGMt6yh/QI4wvRhBNYQIFHQ37AdEqGDNUIQrf5F2Na3n6jYCCblHZ75RPb+avyEBRK5xsz4a8668z2APPiGpUWPbXG4IbecFRZE6/zR3ynxsxHJfRI5hTASPJszbaoTqNmnvlwTyepXSFr87jVPvXh0lBf8Yr30Do/fYjN3qMoOq4Krb15CQ6Ys+CSZVpoxIhlGfmZBrhICDvx2tF+LYZIWZRPpICF4snh2xbFTjooP8zXTymNcBo9c4ToClXGgiQ98/ixiLRXQQFqVCQR3hKMr47NKz8vYTwjBoV1RfIYv6RfDAAtcIb5hzUAUPRkj2h6526xTQgVdg0F8vVwYK0aaSGG1B1EhGAw8tF5nem5iotWvnonkK7ApVgRXWrYvAsauVT4nL1jAfDgT0FL06qEu2ELiIXshGSAtkqeWv54IVVZvopatHVFVk5GPJzX8Y3m7XPgpd9boZqDfZlrQwFbO/PMHdipAFtXElBrmzUmLWlu4B8feqm91nlLvwXoVpsk7x62TW8
  template:
    metadata:
      name: db-credentials
      namespace: production
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-credentials
  namespace: production
spec:
  encryptedData:
    REDIS_PASSWORD: AgDLF0vO2HdmMu8AbRFnVtIERF7NXHbfcoNrwTYTs7jJnvrblG7uZvwCVNBQq5L9tPbPjC9is+iWKrysKF5G6mSyCHWkbm3l6JzcXlRzGvxKvNjlIT86wwzNHvh1Xvyi9reF6Vf/PmZobOqxjljDKJ5iEsdM1UFP+LYDq15MEVV8kV3/rVf8/q+zXCSljaq8yP3/kjHBTbOxGsrs7G0495cE6pRWhvq1G0XZ28FHcbI34cYrl/yWxKgQ69ZtD61lpmIPOh8Sxml6BE77bGAxnZ3HaIzBoBcQvNJ2Fr6h0iO2gYfxQwCqWn7Olow8oVTzx7oyWD/h27yKszX3WoknwHGyJ2wFHs9FFrgGooHa6n8KGHMzz9HrPP5L4DlpXwhgocbbO+kdS/jUFWpKu/Q7wYa8I/HvNdJbqKeqkZRX71SFlnwVeaKLsrbjQJEVphlGLlXBqTJpJIBXmXLjy8IxtbADyWTJ3auwck0+zxXDhaewKCGfmjacNPWw9yoM+9s92f4BlrCtZ+GG8Tyqn8RJ3myxCsjs/QNEMzYZnxzzL0WTODzAQ6lcgtkKDLum1NGLlFIzwhNCxaRnelJZGg9NiipPbQCG4AoADJfAkh4exfqBfY7oVXBUavHXXFciIGhwh1nfkaZMhSskyhFrNzaMp6452KFS++xHCIRxKRrJcYFZS6AEfG/j5O9wJYjgs1pWJ6dFLPs2hBOuNTGWS6q1W1IOYqrj7CIm24s=
  template:
    metadata:
      name: redis-credentials
      namespace: production
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: resend-credentials
  namespace: production
spec:
  encryptedData:
    RESEND_API_KEY: AgAG04d/vGSxduFID3eXnlvD1CVDkxlfQsi7+Qy8tsvRXiVg+SMILNxrZFp4h4+5cEFqZ7uKZKEsE+zdYrFbG4x5A0HMobwM+5UiNudccXepHF1cyDwzdk65uF4yKpfEXaHayN5gDsk8RjG84cAoGgXckhp0hiH9sa/GIJbmWnl7hjfK/G6IoOFKxkQcwrooZCRayjsyX588OtlhVoWCiK42ohVuaNIswrj8jT9DgGpPDTcNw18M+ZO+25eg7ys6B7KvTv0GUXTgEy/3fHEaNvsTLp4e/HYLpR1xgTlvaHWg3rVgCrvdNDcQnEY6eu5s+PnpdBUwYh3BXPVod6OO5lTHqH/beWLI0taZq2Uw6ChZ2W2HHmyHDK58giRoMcPX8VP/dQ988biEsVEyaZmj158/m8ailxDQ1gHHBjAvahjTkDPMTe5tuUMlaT8UnyiFRVzF+F1+5YVj9O/IAf1XJKWFLFBrUp4vJJjnnD1ugVamwbr8JBphRf5x/xxqjy4Ru62CPNiWq6n/wSMUrRTy3gMmdl6y8xxMgxQDUwhqe76bR0E8of6u39ZxuwcKPLA0huKlkwX6NoPzvHwxqKy2boU7GD6tAspqyV7u9dj7i/ZDfSfxqK5w3Q/q5TM7NXVVX5hE+5qkfDZx6yc8vcwtXxEFRSf6RcdLtNU6/yxEIF6SUlVVi7d1ApnzuEH9jS1IxRxyCAYbVJLApFz5MLOTs02X07FfvgkFA3gyFuFt4co+XLThTmk=
    RESEND_FROM_EMAIL: AgCvptnkPMJKqxR+eacahlegiFo7ndi1kB2TxTpbUSPf0zUX5qJpyW+DU0BvZTioGiVsyFBJS8jGLRyAbu/BHLRuI9wtYARx5Bnp1+CG8OL8Dl3vjXLwp89uGeLm3bUaFgUYbc7bQYROkm0/3GWEy10cN8Gv10PlAgxOJ/0448X4WYd2BFzZ0ZgcnSD7ycnqkwLzj7QSemXZEtiaDKwweFs5ZOyTQobbAouj9KpitmopUCuvdu2o9y/QzKDVz8PIyOW7Y/Zq27hg9RMQGawkGSkwNbL5jUvQunDKnBqbmIg6DBQm7+nPsWMlVel9fTBK/ePuitATlD4cUzpHiiCsvwlMf9RPaAA6USvgBFOCzinzURgExRt6QtXijh/0VYYSODgy84lLAguVVBrHzlrscbps2inSVLRH5XnAsZ1CFF6eBLoDg/caFULrvatApEDGZy3+ORStOZegEQmF2PemgmGUI5T2pz6ljJ3WMR24FBb9IzETYFCLtdnQAeAmkdbND+xT1ourMRaEtwsN7kzNGc252WZAzKEYa0ZOmuR0yFE0VT2V6lt9ydp2fO560pYwoxu6G8GBSpZTAOgS8EU7dV97M6+XuUcPyhfUaXF7H56V/eG/XqLCyxi0Vj16s1EqCkr6nfQsN9fmjLlyXPqLuzQ1gu3D8gs94AA7UfRPJSEKhatZFm1rHqoMZKb0nQfTdOL7rDXerRPGl/ASd9OKNeJPh2i7RlXzJOVq2qNoIj/dOvOA
  template:
    metadata:
      name: resend-credentials
      namespace: production
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: production
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgA9kjtynXITzTwU8CT4RKOtPr1/OKvHSJ2J7N83XHMafT70eOhzkpmcuz51QO4TC+TKJvH6d9N/u5fxCb/34wRnBFivzTtkjG8QFn2BoeM/08RD5O2EDcTuqrMU3LDSIbWI7RNY632DmcHa2+Tw6i4r8YQPDDIvSLpiddWKFVueB5xdbJdK8u2Fn1JYIsPn2YREaa8Y8QsxXSTbh7+B+VcuMwDp2tZVD63m3052bY5vvQpfENvpdc544BmDLXPVnqkOcXE6DCIEq6AxSIV+zQ6I4GXBV5vgSECtUYGBPbkVbj4sfZzUnoNyMplzmxT3pjctY4VRIS5OajB7dY94ZbmIbW4C2QTJ7NcyQ4lW+dckX3PzX7cI/CkMZnYjkBNCqvT9/co9A5hSnjPrjQkwii767wuvsfP3igd5lQJ/6BjuAnL1/+SauGHt9co3IfxBYvzl1PD3n3ZFXd6bwGfS+q7uXEU9Xj8tj4BDXihQ71E/NMmVpQSy5U98nWTZQyKZPkrjWF4E48rEAeJ0nMvGiKrZ9KZeQdGnDRYwJWwCg8St8q9b2uzGchMyWuRXqt1XdI3IONe2V/sx71PrbkEDdAz2ILguVPLmChR5mbsms0nXncWBAlTXQvCiViSuhRhpZmKjUnXamlow4ti71oMhNYzporu0AYSPSeRFx/tFL6g6f8iCW6R+deRuMjm7DawVwbCvQ8V3fU3Fa/gHjkeOs4kQvHnsJs+hNHCB4BcNbz0NkhvEyc9xA5XMVfDYuw==
    MINIO_ROOT_USER: AgA9sEPPe3uTVTb3axlI6+MNiSgUGc0RdUHmDywXISnl+P0c1EfqkEsvZGCctIXDP+KihyYx8ebiBno57bUP2Tsx+RdHkJmIjVr6VUpucaSAs45oD51RAfk4hHERXpcVvUJClZEM4BrsOEYvGstV/9KcdfZSBXM6eQfbyeFn2lybff5W2NFtKdPuDCNozvgOEDRAWoKeiSt9ksQB5CLHe0TsRA1s7A6JrZcGZiaxCKO9Uzejw2wpAZ0/XFOy6cQWGjISky+L8urLcUlL08/7eunlSO08QwLdkxj35famygoW5vjcCtKPenyL1ouHiYAEZ1ZEvuy8GuMq4/+9b9Tl5Qd5tZj3uSFDTLY5FWid2V8ecr6rL02POXUuk1oLqg7E7U49qs8+r9ZvHtYNfIbAAEOxJYJdTxC9AkJ9/rpTQPEsauMxih7c/+qKig36zqTohN2fZdBwIbdvBxFXiz8sCvAQ4kHTAX00ZC0D5GhKsBp9qfmCbVbtor2PvyYqSEjXQGgd6rkekcanuvUizFL2wrIFgqaO2LoD3s3Mve26pKchUH38+GMy7lAZo8bcqBQDyQYB9EWgY3fez0W3oC0aRi2z4Y+V93jF0jr3leanIEQinIHXouSBZogzqaeUu2mVh2JMduNGs/hBV6ed0/eM+SsDoLVZYFLPjtX8slVRCg+Ck9DC65lb05VUW/beaZ7C+I00tnqzsXWC5g7n/PQbchlaTzfzbmczNrA=
  template:
    metadata:
      name: minio-credentials
      namespace: production
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: production
spec:
  encryptedData:
    .dockerconfigjson: AgDBZ0zAz+BEBAC4vH0hWMxiyWiZMTCNf9FpKy34ZRppmHh++l3w2MkLPnjBv27aQlbDHq3KKfEYT2LlnVF/v5cYgGGkk2/EUMLvcef1w/3gNUQm4Bn0ANZ1uz+ulCxWj+EVdxd5fR1xYLl0MQDM6TXSeOKIEdsJCyUtWKZjmYLeye5r1UKXK4ybvimV3YxhPcj/+brkIap2wZ4l+XMFDKG5oNYWCTWlkPbiz+GJmsf/WxHyt06T1fq3pDww4z/WVzA+Oz7m5JF9hXWeFaBwrEb+/rvLjU8IE3n1NF/+fwgslu5fDuIwvbOxZG2u6G6OW0+wFfhpvD2Ij5JFYtZIeRaJQFqnD8YRMh8Vs6zZ3e+phwrrbZXQvB+EQDtn5RW6O9RDRpm1D6k1hDVnAW5W58nOVy4nG0CEf/OUtu0tZ4yXcawPnmvycqJk4KuLu8WNBzQY0cU9xHg3NeUMFODVHke0O6RX/BnJHhXIekNN7JEenuFJYUKc6QMZWgrxwvVc8wNKKuQUon/+9YyTy+EcQK6kKRFDbdGkaHTyLIjHGDo14MR4U+IgEhvNDHjucezfNn0OlDZYSzw3T4EP1YKpjnej/Fnq8IEAGAERggRb0nomYv2B4z2QSHPKGIKpaimWUhFs0F6fcZx6HguTx51qmgQ7WeyA3Sv9livqY5PsfHUg/bOKzHnUO2hqWz58CK7qPhb44V7uKZLkdbLa3tTZRmezfiyKrPBUEoFjGhH4T0y42cfrAfUFuWQQCTKKanx04zXgIdrjNLC5uHRL/tfO3Hg/R0xNZ15tj4J/1XfN73GNYEvZN+oSjJGNfX1HyKZQwtHsuB6AKi8h5lg2+Qg/aJpnKo+FtV8BLa2W2BOVIzpQhi0r7TSMq8++7n6xHAGHf3hqvBilheu3SnC04R6gyU93LXiUPfbLBumqpUiAjVrb1uLdDTwX0HxjjOx+GSL+187XxR9OXRHIlHY7HVuIxf/JcfgppFzJ
  template:
    metadata:
      name: ghcr-secret
      namespace: production
    type: kubernetes.io/dockerconfigjson
