---
# ============================================================
# SEALED SECRETS — PRODUCTION
# Généré automatiquement par scripts/seal-secrets.sh
# Ce fichier peut être commité dans GitHub en toute sécurité.
# ============================================================
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secrets
  namespace: production
spec:
  encryptedData:
    SECRET_KEY: AgAPeQWAWOMr0w1vGcYcaV6xx6mk79hrbm20MuK9NqYCIgk1YbgK42TLavNR0r0D5K327/E5aGJzJe8GZaJ4lpfSCzeZqVuP8jHiSgZ9Y9nRAfN4Cb2zsDnShMBm9/zeJIF/XUzjZ5nUg9ymzfjPiFzpGa0OfixVP2RzgpukDlcipytZM3FxHk3a4D/il613ZfMWF5Ey3601CC4a5/PDwivx3bivz38wccnPomDEcAAGiS83Nk4A41EySbWzkSHzdwNrIClmmiNdBkU0GCgLKHz/o279Zx7yYyDZiRpR2n8PEqhCQhK3l8sJcCMXpAu/JXhSTCWK6ThNgC7BjBdbud8ofj83JX93ZvWSOVYXBGgS5FVj4oupuaLkaMoanO3o0xEOtlfDZxB3kQ1acRVLSEneMYwQTfcGK/mSAPc5OjIeAhLcpruhTlevzDamMBwNUsVpC2QmZbB9ifeaoUIjVJDZg0LI6xTHJMevHa3raunmrAwa3dwDVqz5dLIi3pNzl13okOKgnF6CxdNsk3QYNw1uCZhFDf6x7PH07qLk3ubxdxPPTJ0H+8mh+lDb9W16WNKSnupweIFtiVNyyVyCkENP9R3OHIZnKSj3x+iEzqQImGoXBQ/gLPPFX2BN1ohL6Z+pIeQNzWHmA4O12s7PI4taKswKTw9/RdZpffk0AmW9EkbfZMIGJI7H5h+CkcBXCTUxt3s5xGppooRzcw2k56/7cL2WKKGIVBlW7FH/8bHG0NPpr0iTZDVtcT34VJQCPIEb
  template:
    metadata:
      name: app-secrets
      namespace: production
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-credentials
  namespace: production
spec:
  encryptedData:
    POSTGRES_DB: AgCB1zcR8wPM406Xv4KXPMKeln1appPq2STb1R5w8sgaNY9mVx2oGr4PRysS/syIhyFZ/BaK/GGpgyo1110yeZXLWidGRKtMZlfu0WD1lhhPG9AfG8g3p5ajB96ujNRk5agYgaF92h2lM/SJIZeYVkFNdYSPrHFOvGx3yH0i8jxncXv3UQ484/sBYQwnNveoNb2oGrWbK8ZF14EFUXLIUdRPN4s5n6XLxE9/Q5GBH/6X1ajvTQbhELf2NTykDfdsIZIEu4k0aKqIYxC5A4lFBE1iXDNfpvWpBA5g6xNwfE1JXaSJOT0RfFlbG9nWO0TVuXkhxSCVZ7JZNHqq7Xx5UaOp5Z5VGxG6/L3zfWMo1EaROfwQmukIiPV6rTI5sN6mVodQuKa8WxGWTERhP445fRqCk2SUfTKcIKpbkcK/Dv+dmlmx1eFpK4A3KpH2YQGy8pv6/0Z+Iu48bLwld8sHrHs6lPhrawJ3Cmi9K78l72YfVG3Ja1gyra09TZU1XumT0DapIhW+AUKJyRTe+v9V/wBi6gmCu0zD4BO6HQh23Bjn6k4fwavsaApMG1Uar6xDQ5hsp9+8+zbZ1IjjRXo+QyddWsE4ytOa0kQB5nTnP8FVCzr+kHRDGkJy+dtgOneGoh3j+YWoJLWnUYpQ72rvWebiYS+KrEZstNXXAH/OAaf/uvzHelM7UovvZGbRrNrUoBVaGoMlMQ==
    POSTGRES_PASSWORD: AgAWI1BUOY0ceAcw9Shq2vPTYlfd6p+wUIlksRxU6ehYrllTMBV7TCRM60k0gaywr3Vkndo1ax1oBRHhycuaJcdPjb54+NTWWKpX8Tbu8/NssiIkKMqv2vlfC/k3zanlmwr2sPSlbljhmEqr1ixOlDVCNfS/khdjzGfhXsXwyvjve69/R2/0JRtQiuanmtkm3C1fXkB7ZHIA9bWnQ7ohpq0bLw0tSbPMsaR/O6O2k7nJUCHcedGU4i/lATV2OwPW93krzUNJuI36rtzfB3RK5+H219Ed1reLklNNho7ElTF4p080v11y1gBaM5n1OgvSn1sCIWQmsXj4vSthp8gW1PBe5oG43yQDfLrR7iApQezaf2TbTMC5wX/lIbFlB/Ewt1wb8JKdqKSU5P4J1/mnCgxtbR7XGvas5JQ0gNO8GYmsi0BKj8N1h11IcfUk/6n4JlJ+n0kZ2nC3o6sQaSbYC6Zw2dcSuTLZcCGFer+nq7MDWoBnCcrF30riPIoZTdupaSdJe4U+cdy8CNmUhitfwuZFVlxtjvIl0SKdgEI36wtfql4ncT4dPS5CHOqZ+Pea7+yM2b0ZOO5KkTZRvGROphuicGRK9thLzok8/70dk5FYC/2YwotJAwe/wcd69UGQiOQoe+tCR2A+ou/9/Ex4LMgLVza9IICm/PSZOYxT8kmtNWWaCQZTHOOI6tijKfiDqD/cGHZh5WksEiS7Zy0faQjc3bMTyPGirhREFqTiIAfSaB4holJxFBz04M2VtA==
    POSTGRES_USER: AgAUrvlK4ImA5fitOAVk6cVW97NTGeHmeyUp7ijsrEY4zr+nihw7Ez542H8jO0054PVHzxR68Dh2jGYkvQe8kRC11qpxoRVDJUccbYqIr5SpBisbCl0WMJQRPopY2agrvmN8svpqJ4kDOc1sl8xtdw0D2QDtq23RGA4zPLhP+ldSgBLGq7gLSRITOi+RY2n3KZh3ZR3QqVqBMif5Xj7P7cSawOAZmKBHbqm/AtZB5XVwb9VS/n6YL1rjrJGOl2sKwqp/VtJZJeVWzCwx8eKfSV3QetoEEMjMELxvj7bRUNDjIJE5SV973UZ/x3GVAG6G0mL4vgN4UTxn1pjSO3vAjvddklKhzfbCF5pDzmk06JPw+qL0hnywPV7Ec3pWaSdVFPQxAy9Y2LVmJ/IyKx0Nt3D3Iadq+qbSofCSTg0PqnaVA7NUihjKQzCzVjQ0rRRToTUsIU48nk4RtXQ4DBPh/bmc2gLOSoXX+WqABgYxoK3TGpTOaGCyAraM2zYLyDsCKyN9yNcJaCTsZQo/UW5cHLW+4rCGvndEfPWhDsFNsnmXEZBnMPYqVgap+a/Kpqy2yHXdeOlngzlmAk/7o2p68mvWHfZ9rZ69IZ+ScTbZ47jhfjQHETWZUSE5GNhxhTvvbPT439ps+gZsDfuKLe+L/+e/gB8Yy+lqd+UJ0lrvIdknCK770zjn3Kht2KSpw88IP6Pbs8VXa3DQyxXf
  template:
    metadata:
      name: db-credentials
      namespace: production
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-credentials
  namespace: production
spec:
  encryptedData:
    REDIS_PASSWORD: AgC0OaGn8I2KHVTMBRisKmq5wI4ntrCQjU0ZCqvoyhK+jrlWamu8myFJonmvaTB0ZjV80wSg47cIrVZaE917PTEJNOms6tOIxSthDMFeW6e4BjYDwi7b3XXeObMfVWRWJZ50Ryxj3Q6lxxhGJAMdxH5fYOxVVlTjr6Uz17E6R8pyB5MjHwWNrGAbdqilS6k4lPuWJKHmfdigD40HQYBb+jq17I4Qf4BNJ1FyNWvwFGs8/u46dwnkCxjLPPClI6MT5oxdJC37soCf/3L9vi+WU1eoGdWYK2wG23nAMjgyLFeQWFhuE4mWnDGKh9mahKN1IEXhkb105zL83Wx6g16OL2dRi+txPzJKzkKR32heUd70gzSQpT3lik9MABvYzm9pAkoZ7NjNrbVhmPe1CQtpXJoECi3C+N3Qj/+iVh1DkP0G/cQKsLEu4kpVhKOGFd86e8mqbXkAxDzFbvtK5aba9y1dJnGGweo9YeQTyV/2LoS3GKFYoV/ngdMAPsNikXfXXyYUft4rUceGrKHp2JzHye3C2cEs68TlX2ehtiwDddeyXXRg5vtrkZ5wmXqZkfYlFlQ77BuPb6UFzIwPX5ILoJfvSWeCknCyBveSsOD/OW9JYs9UGt2v2LCnL+9hLBV/qMood3ypRF8W9/1yixGMQuMpLvv8RKfHn3NgKqjyx0xiKMyrRUlXGstmNZVhwwnVn3HhzTNjCTkUqZ9kH5ykAQ1WJRi4bUldga0=
  template:
    metadata:
      name: redis-credentials
      namespace: production
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: resend-credentials
  namespace: production
spec:
  encryptedData:
    RESEND_API_KEY: AgAMrJ5DdM0CIZrfOceO7mmBxbx1krNblcr5xvjYngkPoaDMTdSPC2OidDLwCbTKCIwbHvPS1a+YHNDMzHwr6UAuNMuxElE74CckuSpbsNZQbt/5tDmLrBApr9QwK2BeHuwzPFav1atks6YuNeC72+CimN2x2WmhFdY1o7LCrWFQgmJkdEtBiyOkMwdpmFtAnRML1dpU9LezFlY843OLs+KQ8+WSjUWnjQT4lB9xB5sXjcJS9+sJdmj/ijBSM5hfNpTceby3BaEcO7Ld6GHg9BKWFGc6DGoi76GMx5Ftrpb8WxylSqR3aWtrlJ5CvByzFkDOytPhNXXGMit5MepzuSCYYA6LV6V8+6Arw/qRuZGpMwruiNxtOu2a1hZYUN63x/gXWYP1CpRmOl5OhTMIQwxbtRWGHnR44q/ovXrRr7J/BvYDFwTcAOwOhk8ZkwW+nVMP5ptFzzxSfa8mO0b8d948nmzvNZSJ2eNGBKdwMbchVb5oa1xkffIbZqyFhrrwb8Chdx2zAe+kkIzOrt8JvP0zUsUSsh092D+BeqBxZsn4iukB8VlVEIK99fi8DohU8/AHWjeDnvO1+rnc6ppblv0SArRwxXguCCtzC2lY0mNFk5b9bCvBaZLRk1it26jehf+F+piYaz3at2wgm6SvsGbLaxKZsnFa94jNhrgvUqYFk+OZfT5hjbDWnquGKvo42eTKNlZgEXw86r3YLutCbwy2EF236yhy685aHW7aa277p3iYa8s=
    RESEND_FROM_EMAIL: AgDIPrNlPGujSfiJ09h9bjitKk7HCCTEVeJqHe9RIx3pDoWsDxMqiyAIeb8rK0MrcDXy6idp2foKK2Ljqh1khFpWKWa1IXBhbAbm32LBCX9UTC0sn/+l2Iv2AYOwI7Mff3EQGi8n4d5bQh52G1uSia8sYpt7lVjh0NOoQPNh9U8G5BuTF1UplNbygr9KRPy509QDlevd1EQlykc61bxmZpY/1iJi8WNXU0n4HnFY+nTW8D+VCG5KRJZBT0M++EVY+Dmp0MFw/y6LZlJ9n6GF3Aao+wqA3T0niIYt/XHxJfWRkNuGY9gcERD3Td9MC9AKMo1txysPl5cZSHVkO/Oz5ihcFAj8DW+WbaTXsoP7k4wwkezCzGbk5BiEO0mk1z613ot8AjeERNs3jkDAWR3ABvqtKNqLwMUq86zWyQuSLipM8OAYH2srG/R4Aw3A8rCNSBc/3/tVXJQcLLET1QmBE/nv3oFsaK1QuQFEQ67kanRpMmDThzcUWPjRNt7J6YNCLBpZdPx5/olPPzBSEfSktPRuGOF93vMtAlJ/CnVhlS3/Gb0czV8TJUXHrsp5QBKiaEzZYbczavz4UESNNWUFzA38tYknvw4n0fN9LfJ+AhUkOZBaCf1RW/bsC0T64uIhQLdtsgWhKsNXckpJGnxMUqjavLN66w+79/mVmb70Qh6iLAc2pE+GeB5MscuQQcGn2NO1oLAqnqJ+xnrvhlgzqNo166kEoSGvvZ5Gzog4j05aKxdw
  template:
    metadata:
      name: resend-credentials
      namespace: production
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: production
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgBmToTP4bCokUDCMCSBFG8eWB6jWP6jrGvrh3qQZ8w5YQGGm9RONEOMRvBq7Kc5IEBQ/w9Q2XDQeMD12Iw7xj2GLehA1hgxEJvF86OwS0nOVPIpuFI6L0EeTO3S9v8toKOVD397xh8s62ALkpYJrsuZhQOeyw/Xbh5Zxfn4Fl9m8TdIde/m67QMUZrDWEhoc5tMUsswHW6oa6MnHWs+edupvRUgCQC/Z9zHMzJqNDoweW3bzyz+w+il9eYiT53LmZ717du9dh7Q+2utnFngbI3l4TpQQjCnjq9wg5oMIlepus5y5RtHqEY+AkVIatccdeZmdMohHH+6+E06oAf2FeVZ2KzTyfPAZVXITmkrHqWYWsi1gvZ05sjkv4y+CkqMz2mChgdF8GYxTmTj94pwXvaJ88CCtpNLMhjhNVxBHrx+6JKG31h8g5WIBE1g6hjGp6m0s30WP62ZeK94ttsTGDNoDS9qyeMkCxR9of+SramUvFibZszke2gUail7CkMCGg/RJrleDbXul5PwdsDXNR+FQyrA82opuiFlO7az06imG4OkBkltzUErtM6w5qGwwgsEowALPjzevAX1KrD1Lo8ftPvutMW+s5KDcvlzSvLSnE6e0egc/1JnTa7a9h1EvOpt7tx7iBplZ0Uy+76J8457TR3XKApd6AVXbiyESpmT8F1lyggmSRSlc7W4Vydc7z0uGh19Y3NrMSHt/e91YnJ27UeM426DumArEVBfTz6syG6Dbg/ziesz63+gfA==
    MINIO_ROOT_USER: AgByzW5oBCi+B+5qw0DXahI3XlVb/S9yuGaTmQRz8UNIVbeqxo41C9FkKYnB69bQH7OG3xF79bSCz7q7S7jJoVpajI1LqIC92g9Nre/04dJZP9rAQAPWAgHjX7QG3u0sB57qa9hte9bmcmjZvAR2hXBLlhvbmN3nr7n5j0ZHISSe0UyCOwFoQF94Aqb76pjXSc+p1kpeNizenGKakS6yPC7UP44GW++l6yrdBjaAzf5GWHb/51RN3KzSpaEh920N6+4hXbCqdthJkmqwQAJWRJW6n0aA2nc7NH215bR3TnM+7YQ8uoreB7bXDxVKKc/Gg7U6ggqJob11Ec8FqGnYq8LukU+47bKGoLmKw2yqTSYNc8J+OYTs2jsBK58ghTDnEsP8V6G7t7n7icyGobDD2ITGAOKm5lv16njMasc7EwglL0WWHEMRz0hR52TKshP9J8QAG8RHe63/R/t61nvQHPTTisYIqb8O0axdRn7YNT4uqvvq7zf5WbhfohgU/dlfyiF67jK+XtWpKqHo3TLG0HQ46Q1S221p/ErGZITbVEOXfqUuyeGqBUYKP0O2lKN/69JggsWgBmY9EgCM8jhZhkMvo+4I5EgfCqAm0ld/YoTq9jOPFaey+Zs6T8tP6/5dVRDQGB/XMo00NHWn5h0/57NfsJ+r/Q6mgVSqBXpogQ33DidjwFS7REfToetggEDVRLmLiilbslVhPPhTcTRZnhY2TCggv3S/n2A=
  template:
    metadata:
      name: minio-credentials
      namespace: production
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: production
spec:
  encryptedData:
    .dockerconfigjson: AgBJM55otEaEfQaTsyZDaocVkqHLGOrhYmo6F5W95Xj7uOOA4VNSsI6/J0QdnJq+HATsD+J9iQaUPU1WBAOCqDeeWO+IEZL6qW5m5V1Emd6gwNEQCqbKthNh4jLPkf5xa71quxi3lut7Swm1ablt47P8zvM/4CzOKyiWxEfw0y0chwOi/Xx+wtNP3YFr6GB3auaM8XVymQyQuKYT+WISf6LgojcUnsLWhsum9+GcPVCScus6tnqHMRhelXX9/6Fw1AyZellfn636OPJOF4ApFv+efJ1BLDFHBuZ8bpFO/wIx6uWOpN1Fhku9stepJfaNdnwGu/BW/6isx0iE/Vt5uBpZTalk4XRKKE00OuhmXLG3YyNlBgaOEpOARa6RiZmokMd2ymEUuhDSb4Rk4HTq3cpxa9GhFb1K7UWZx9IYRNd/06ZkPFtE4IgbKxyYAZ9H/c5LuMcXyExGI+dv1gu/mPe8sMYkyeYcuD5FDT3+nNyTmwZcYAubYgipsk3HCJz3nlm5pf/Lt4ORBLwenVB+Ee0O29L7fsryAM/q1rJpQg8Q69TiVMmQzfjuPV0nN70snTpCzFPzXPIvpV8W9/HEqEZ++2pcohiZAWphgMUTCcDicsGx23MuARqIQbzJUOMWEEbiNr+Dw00pnS0j/0k4xxra4jwwhlgVcNMRVib+JwJu56jQ9TReG1qvmrz2Ukch6SAi3YucaAiMPgz+K8c/PoUNjOrfZBavMvQAzUA7JYgENLv90KYX2VxjxapaBLpiknkfTeSNmZIImZTxMv0pTteVchhCnsCKvDHJbRexQh9lxwVdmZrNpREIlx/4Q1fOLPvqp+M7s44EAKWv9O+OZd+GIYnJVkah0aEPpp0KlwVUsVb5BVRs2gx8NohPl/tN8Zep1Y0d3g935Q6kwP4tZor9n3fzMHgB0O04QUMUP411mY/2i5/4tVsarr5n3fsIWXzHQDKhorHCBDumMcKc/wKFR/ITbDsd
  template:
    metadata:
      name: ghcr-secret
      namespace: production
    type: kubernetes.io/dockerconfigjson