---
# ============================================================
# SEALED SECRETS — STAGING
# Généré automatiquement par scripts/seal-secrets.sh
# Ce fichier peut être commité dans GitHub en toute sécurité.
# ============================================================
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secrets
  namespace: staging
spec:
  encryptedData:
    SECRET_KEY: AgAcb1Bsg8hAePBp60CN1HexziM6R+cbvcsKKdUaPMWFkaWwi0FIojd+VG/JHa9++f0WfcdUcvQmAI0ETvRv8pBf2u2OdBQjHbQ+d9vT1CRbGVQqLnMQ4ltiUlVvW1HMeU8gWITOg72hGZg//jLZJ/g+bEUFrL3RTOoMYsnU1kk9X3ev9sfI3gmmqUIyuY4Bl8tFVnkZnbmwIIPEQ7zNgT87h5S9KSBkNQ3pFu2x9fvTHwFQtIHC3iuImEh76AprCLizhuSSgRRIMkUuFGCUEF1XvsKKxHzx1Rbyr6RjZuKssfxJV+5Z5+ezd7E3BZU1Q+Z0bFjmTWY0GhCuhrwjZ4bIssj/jTJif07Fm4iRvmMzxJGbWg2qfqQnTBHlRDJYU4Jmia+6s/Dr4lQ3FaEkhcfk6rtoss76wg5EI/jvOeA7UgCElLi7uI2jOJEj6HWHSp6wUIlJm9R9drfAyzCXLRt61HzlFQ9DLUQua5rJneVWag9MA11jzV0bUSwql/DN3unzEhovMRYWpatIU1tF7SzEjfCtYDHPMvOgaJjH4pSeqccohaughnr+zUNQfJ2eHBdUHiBY2YOLNlYD+KKN9XpFa5gu2OAcMdanL9gHnyDd+XAwZqFh9ZWXNjAI/ORjVlYembsbbZkBdXuRJExfy8CcK2Bq5U32YIibiDdpPEOY/I2OPwkK5f36XxqSxuOm0B/P8pGJ+FN582f0KV+y5R2Ql683wLom9Dz61ewoTtDzubbiqxLbzlDPA8Hzu9a3
  template:
    metadata:
      name: app-secrets
      namespace: staging
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-credentials
  namespace: staging
spec:
  encryptedData:
    POSTGRES_DB: AgAY9EZZlcUSIhHDsk8vgyoiCdWI+2VgTDc2w9as3yBM0cM59h201TaBgn3NC32YOgqxkv8GL/d4RnW7Ya9PdL7yOergj+wGjiCkFSxhRlexksT5sSjBikYM2k6hKwE3neFLURiyGTj3VXrBt7PNh2/wO1aoCcp/H1z6Ht46bIGYRty68Wcdkp5vFpAcKkyOiIAQwhaEoemPJSsR2RFKX2KN+ZeEXkeP/CBlbN682lRQrW6N1ygofqUPbMCAGDQKHXB7lPkcABVhAhn/DRF+ENxg3bvZgq9CIWwo4D92NFH04/jRP7D7i0OKV8glOANhqxisdOl1h0COTLF9RIZMWsfp2o6MQWLkMYMeV4FjbVm98DbL04Zi9Z283uSl22aK8XfTwccrLGHWRpL+h3x2iqX1hnLEDqb3a/rZ75iBOfnDhnN9ZqorQ/1miJxpYZ6x8eAOnF6erS+Fbgryz967yrBGJbJiS4+6XdTDwE+QlbZX3eOGi6txs62sejURe/jIQfl6FWvB1jMMg7pBOJjgU6Z8uN6sOgNUcHY2jqDSqXiOogmI9YOIc3ZvFi/Mx/KXkBrwjXr6qqt1omqHRA368liYKG3O+lIT7AE8kzaUnGdALtb6IvraIV0xuu8JeXzQPnC6fxCngb0G91mYsDKxK5PXtN7WjXfzJHyQB4yYHZRMC5ib2IxR1WYlOZ7sBGb4Uic0YcLizw==
    POSTGRES_PASSWORD: AgDNCDfWnDx/OOCZc8he4Oa9aZKxfPVsriv7QwDj1/IAOc1YuNPTqqkPAi4z+SiE9hSJg095MLVHpFRPqbCGmfFCIOgw00Ho3eHJoDWjdRT26lUSvPrmG9MtkZeKXG+Y9RC2/Zr6jj29B9BT5+Kh8iyBgzJesBOGyJM81w4oLJQ+/wZhQth9M5dZ4xhGgOf4nAfjHxAJfYA5XlQp0kOa1+MlG24E0OQNrqTnllyouN87AacurkrKjQFT4pZ13JcOLS9SNhJsVmDqio3TNEhNUGtNQRzlaCaLgQqImCOqcopvfO55nQgZJHdV7LIXzEPBjzNb6+zLjQL7namW2Qns2kk4EBpUjwcwXA3wAcfs7oYL3rUaRuegyr5nctCBdgfjl8FAxiuCu3PYCWjpsC3GMUVVCusCwzsN69qFxDbKdJZjWD2hj4j/CyauC06ibpTlBZ3jxgF1YZBt2K55vBqCE1ZW5ry2q2XT0uIJQD/Du+xq/d0y5fh3Cg6MdJD95YdlbL08iHmdhXfTYbiJCPGBLomKY4nnYTxiVVok1g68E9usO31kTs1zE9X7wOcLgNCF73dv30pCJ5cRBhjy/E6+i616a69cHuuoIhHJCOTQCdEwuKYGcAmvNtMtpwEcsrHtKfI7nNkiKXmxZiYF+1gA/cpyKjU8plAJP/lCzlptaywjB/S39dB1HMfZb7J6fIF+q3FlMNQRBgSWCRP/Oj8VkyRubNEfLj4ppytJtmjWZ1BRdNjgV0PG8C8FETUhtA==
    POSTGRES_USER: AgBhMlJjEKCrSEGzV0L0Q6ryPaDNYqH/pwmp66FlldwqAYAykWepaNmghbsgzm8hmE+aIznjzGCIbnBqLSQ5LVUD9dcjobYj+C4OtVuwSB+19jLMrO+EmPbTltp7Muhp348fUq3JWxFQ0B1WxEApX+1wFYkPqFWc6U2RprPtmj5gUsHGoBrp1hBrmb536UUyeOQN7cX0ROB30lMDfbJq4YAAd79m53/bBkkTDCsWt7UNwqwi8OLelvvkDGhwZO3PRCNiSywp2FQf+mn/75luZbC/GxtLrqYic64pO+1ot3u0Pf+bLRQFyiDS40spGmIAqMNjpbbNkhWJQCf//nRDrmItXxP4TuzXo6W1ir/m5nZCUCwPLvdcOwa6FeXrkjJsTk8owe6u9EPobzBhRQvUkK/vi56RpqV4IqR1XgK4gsHy9LskZIoPeXwdnunD94GT9cQCGS7yO/yHhXIysEYHhJsBdpHVo7DRDnXPGUBaCX/WdXLBJohRTxT9zmKyCKvXKzgPM5/QkbFeql8fyksXamSvXTGWX0wyZLPeFFmd1Zm14AYKiYNwqflmgglNBwE22cBfF5YIvABCpzg6l36e832QDYdzgF1m4i5aT52MLwxHHvIDIEz6QJT+Wl1BeWXHOkQmjf41NcZrsYbFnHhtfjnMaZ+ZbvFSbHZgRnDwtZ38PxOYvTLIrMDAc2s8bfh3Gkaxr24XoDn4NXwr
  template:
    metadata:
      name: db-credentials
      namespace: staging
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-credentials
  namespace: staging
spec:
  encryptedData:
    REDIS_PASSWORD: AgBIaRIZVMurAGLNEoNUTq29MT5cTR0v1JKed82bOmghO/Ph2qnug0F8UgPIYOEjxuuC7hSwvqG01JizfmXKFe9SjD3vmu6RlKAYYwjjFS6ESrpxswqJhrdpkuohBWc5++XJaTs+Wg5Dc1dtwSnG3bsqUvacMdcVJjxa2jzlK02NHFwSFfuwujYS6dYWQUfoTB+il4QOD8oSj1arbPzfZrTUczlHz9woVCy/2s8v1yCVOIDgaVH0pslTgZq3sRXIU0ggOnHxzH25u3LisyUkfcjQhBMpApN8v3LDJRD9d5W+pp4zhRdS/GggfVIb/0NHYzNM62aksoqgv4/1dOiHeLzws/3LjoFjgp63kM6iC0mVGeQQEMOXgTH87gH9CK9dYoYJ+RWQ3TZ5FmYRKB3TG3HE+0fEoAfPWZmtfJcHT9nFfO5jGRd86Iq4gIQq62YhjnXlq30ney0Alsldxc+ulc1ilH0F5RZ1PbaXithYqUbgAA+Xfb/Stzs/wpmdyCZXpsSFoLWCIAEpmAX9Lp+dswH8gzW370Yjx7xupaJqmWOz73LciDYsXIMh63z8gBMk3hxGmQHIEjxTHQSH+33OkcFzzrnbsrfjQBFcypPxRxmZafA7MRWtE897Y/xiEAtHPire/T8HLeWLRN8G8ELrt4fc2bXsqR+7UMK2+mcJu9Ix91UlzKVl2yiWizAucR8cIuh+UcRKCBZp5hpijX2oMBaD5rPbmbSpb+c=
  template:
    metadata:
      name: redis-credentials
      namespace: staging
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: resend-credentials
  namespace: staging
spec:
  encryptedData:
    RESEND_API_KEY: AgACKbr6HyEBlVxcGTv3OheSmbHOAevp/iz3ZQ/mcAXIZ0HebrrMa5AlgsaLBY99eDlW+9fLmLYPhm6JWW0DClKyRvbGTi2xC2FYFDbW7xdxW7mugMcvR0K0UDsqmFh7NE+9EeJwn69xFTgELmMJLJPpmDWm2Fn7nAx7CkYjRS3u56l60usHOOle3qOEQcc8sLINGkX+4mxYgfuCpqV43x8IZVzzpxzywJdGo4jwv4S+NfcDCj4xZju5ts7iCjjf2TRVtgIBC3T2vFaF1DcQpEFcgiunzU9CCVnYTdmLLF0qa2T316KKMsR6zku6cTnsKqAT9lQz6fWMf+PIdtndTGrevQBL5P3yY5pfmD1fNCgFCZKZRNUsq9tMDUd1mh3vQEJeBUd3SRdwoDj8tERRH7lu7VVAwHeLp95vemAXNOEmnI/swcCa44NJScgA4vXzVRN2ACjycT4uPGsYOBJbjzL7LF1rEg54GE8V95WFgDLaZDMYHOWzbXMrHeqWWIzk9/6qCBgQujKBYI1zu1X6NuJ8c+q6CXxt4uPIb6dk3kbYoarv+f5j8ryNjXg1qeArqJ5aF46o1oR75SipS//v3r+J8cRtjitQ6H12WXfRYgQSsYBsQDvYHfeKn2ZeskWTPfPe0FQgZJ1TDUtL2eU4Dt5GK0IR+cikCZTv6fz9OwcFjDhjJzIu7FQKY4hpkszvlsVpu544mzm2GaDMuANle+sXLQv0bJq1Dp5R7yEl0IZ1VDroJ5M=
    RESEND_FROM_EMAIL: AgBfPc+wW8coAPC3F4toXNsimuVRBd7lX9Yl4kcEQv/N+4OVmxEOqHThozL6Cs/oekebPOlEN9CWwLUGNPw3y2h2xlI7505J61pbFtcHi+hkH9c8NnEx8BHNvujvyXsFZ2j3y4p2IdbsLKwImwqfznPTeeQP+5Qs8CCDM5FQ8QFwy53qjYR9vOQDDoOUUqneKfuAsU1sWmrLGmkucjTIYcEwz64r3xIO+wDQc/tUX5zX/XKL4JEZrQIb2LPHDIz4INs+K8rONnd93C6tDcnZK8TadJv0iaffzm6DK5h8aOmgVf+ggwweS7UhremjhD+HHKFHi0wrxl8tfX4kNjVESiO/+GsP22WtaR46gsf6Tct7dWsKA0/DYM87EzXBqPwSZBNPnQFcOldKU6JGTKlxCdq6O/9r/669Xz7eKsDthQ/JtYmv51uIZfeqBFZOhpOSDeNUlhky0/QJ8E9AfKzfiQXG24ZW6q/qTGj1UFnxtNkrwWdJpeqQ1b1gotxDWJNbzqDKh/ntNaRvuWREuueSERTrxJOLqYNiW3uRtlS0HL51xVxt1Hjz3WddHkMOSRufLYT57xYQr5IC4tvMeq8TQPTI2L6Ngu5XtAhI/JGZW7FvAcpS27GrMIN0usMG62AKOGwHLh4hZQIp+MqWENKKOgOPUSMr7pV+tFZXcaIoGWCEYqSxqrU8kox+r9BCuHZdmJLCqxYdeoodycwVOs3VFh8FWK9VU3LLCX4TqdCrYxPJJi+j
  template:
    metadata:
      name: resend-credentials
      namespace: staging
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: staging
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgDCgGTD0xKo4P/Ms6erhi4mQ8A4LVLuX/xC3T/tOVADqVabcSJPE9+AqUgGu7EVEPqlkTZ+yGeljwPvBMXF6jraqJLaDpBVgX1dEzuOGkAESxi/EmwcWMIbfiAXOAMQGzlOhoK7R0MiOLdSRnsU1bwWGZ376wOfv2CjXzGeAXK4FKt4FZz7wvt3sCEmyQh1K4LFW4ejfuWpgr7mFKxNykWlKvBf7ZKUaI49wUR1wb010uNfYR2fLS1NxgeJbLjRYCygHXM+iRcZk7vT2Fg9h0/kJ6swvWyFsKSQ1Vjix8kO2IOUZvVNKzn5ZHyywToCrloz2cr0sDHgeizK3+E97uDY/Ma8tiow6eqnBfczicHHbH3Dn9Y3rBcwL3JlT/MP0v3F2wpf2li+Aq75QFIL7rAZnTPOriYSBmWwZZRrlIk9e6E9kdYtLuFUwC3pcJOOzkvtcU0MG8n8yMHRYgrELyveWJ4wEKeQwEjgrFip3j00KaSo2NQ2vDWh15jDfUtS1yAHi92LqFnSfdU1xOrpbd+VmxD8Ji72JRpAyK3NpRvS46pTnThphzz+lhnza8ktSo63xmgwv0kPJn6jNgParQ1/ULVbxeY1orsmoK++IrRWZVk7R+gadYkbHo4mX81sdzfUx1mOwvp3AEiHGuSv6i1K+pDTYNE+woTzHNf1tKvgX6Y1fYYQe2smuW6zTg9SfYZvIAZZ1J7vS5O5Yui8AVfMMJ1oT5q9rRxfgZfggTNrxL40Qh1pf67iYg==
    MINIO_ROOT_USER: AgBH8DY1hokg4tdU/rKEIoTB+0p6M9SJUAOI61zLpZ3IZZF+91JbseS5KrTf2X9sR/RhB5B/MEhjSb5FsemmBSa22AXCFQy6egzvOmNNuAN0KarTZO8fUI+X4rJbFN478psah/9G4SsRt02FVfUc04eCOOXUtD6IyuYzrq5+g/WD98y7iwFx2B93b44TEtNXUTvZ7J+OKoNdzoMeHFUePE16zOL0Afd7585HEEOTvspU2mSjHVaZiW4cwrBvEyVjPI84kSxR/gAkkzzs/r0ORz0OIUZDuot/BABGXV0aceMz4e1tP7hFXJYmjc3fHE54Mks+5TVjvM3sjgWk87Ydeozbqj1D0qHfnK6NpoPPsGjFACTMeOJPkMAmFVZAfAuqSTxc/1RMx7ZpqQcP2RCbcPkyORoNNpTc1ZNMhLSwCpEZ39fFKQ4cMY+6nkA7TxOI2luBOjDEzzEIS+YOAFhmSK23iIyPO/olrzcDd9CFZA8+Fe7wel8rOkIz8i0LQSufBOZepc5wg1pJ4/fH9ES+RmZ99EWE3EEXYpWG3MaBifLPr0h5oc2DVNjOhJitmvjCSJaQyXvO9YzLU7JcfUkgHHfpvHvyPVICv/xn45Tn+Fml9K5JI0r3B3id6lbR23Zo2uAoOqCnWckDERR3xGjS152w9i2kgMWqfEUprbWFoOI08CV34LN/jZKFeZIcrxCck/HYZrlzjCA6t4fT84lYbC59mI+OTyY=
  template:
    metadata:
      name: minio-credentials
      namespace: staging
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: staging
spec:
  encryptedData:
    .dockerconfigjson: AgCGuWML3AamuNeOcpKGNTLysUf1Iqu7Gsg61GQHyviX5InQcECGCSGeBlDohCm51AZavEBxHkus9wCfyJug78BdB5oCV9oj4TfMUJX2RQLzBCUheyQsm2CL0rbHbHpPkeSOrz0bYl8utKPMJyVGddthmp409m5hG1QM3Ko5BjZSk2SG2lF6Fn3fJ/NY0mN5hs9jVvoAIPGH5Ddn/XEDoN6GKu8YeKO+A20K3KrBPIwztKeW4RrNm5ACaMqPd2sONfpSo5jHM5L1qmHoKi1dmsXBlVCRo+box1QNIGWkKmxyyrAb85fa/Kp9q7MSqlHzMSKNlZxIO/pRXJS1HJoIkzIofagJKZ7LzbNooSjEHiFTViGQ0zSLAhRITe9+gNPYxRuvFtjrahRmwiYxI4XR2qeaAHvvmnDymJUgsbFx4Wch5LogQtDIx/Rq1DWMl+EyaGaOcDQ/kdHPT81dpZRcYdDuiL4Warbr19rD1QsjJqw3p6a/UqEU+teai49jwMZ15NEi022cmkfhNOVdMsR0yHqGJ0pLzeI9ThJTXA15EkYqqO8ySI1Ah969cOGBypALWjPGG11dbUYYzz8ZTOKaGWefv25Q70Yj4i61sdCK3EnwKC2n54mfZtNoeeZF1KeOzszAif1bR66JsK+CjbP4FIv84ygyNtDzNTZe4pm5HFOof3hT1l0tsgXXFtLq5ZJa3rIevfgufVN1Ho39Ix28NJ9C0rqBD2PQBYjULHE1BJws0xsgsky3Gxm3GUvwt+U0gFa3MzCf/8pjIenlcFNfkjHvOls/pdcgulbmX8w4SziB4TQkRu9Rb1SUhsaEcQNH4d1Cl5fyo6WheYPv5NLw5x0shqC69GHx1aQCO1+FqWmF9oQvW1JlOOv38MJdeA7hvjHcBvu/nJf2dRuDUhsH0vKj5e5d4zMaXCaWzpL92S50/Aij9AqZWB98qaYg22ydrxYEBubK010YVuuJ5343zwT+keCk3RVZ
  template:
    metadata:
      name: ghcr-secret
      namespace: staging
    type: kubernetes.io/dockerconfigjson
