---
# ============================================================
# SEALED SECRETS — STAGING
# Généré automatiquement par scripts/seal-secrets.sh
# Ce fichier peut être commité dans GitHub en toute sécurité.
# ============================================================
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secrets
  namespace: staging
spec:
  encryptedData:
    SECRET_KEY: AgDHfE0WC5PsXSizAfAGCfMZMSSUIM3Y4qzzOKxZQznpVke/u/ns5sBK9Hy1CVEVCE/SP0fSua4t2bOadYBCBuUEIjM2h0vfxZ/a2OM4+2AsX09KbcFNafrLEN5aJ8wM0fbSGtrErFuWb2vaoMbd9TW2ezwBWIHuqdze9oTYUyaL20FXOSN58jmh/uj1Aw5erZcUvwdZFKZe/ZoTyRUBk/2kKoNgPBupAvRzQCQkYFGKnAQdv6Sr6Zkdn0qfvWF3VTwRCe6Bv9oZ/KJpAvimJEAOzCNMPlBfVZtiXuHZGCrMvKuh3pTNEJQopENjoSqLsOWMpRx74akQI5OstPFk0+WsMI+eoxhfhaUpNw+BpaBqJwfdFCaRriG4J7xF9mLR5W59yxrxdJuW6727MhoCnK3cb5JMO19oIDD6KRFoPD5/yNbcchSwSP9XlgiRj5tpmt1XJ2698FcZg+cD0grTf2nZiP60w5kJXFLLfnMlaeDRN50zeMU8QVag320tgNZ5kXoxn+/Kv1vlLWUbYcpUccK89x//jzJBkaliwYxhGHkgGaz2QKPSFbKXmSvVRGBKrJD6MCHg3rnKAP1Rur8YAlPi5G1aaotmkJZpKv7gFxv8Gx7OsCpef9vGoiOrEY0dUqlW/X71wweuPJe1cTFYs/L+piOo6tq0exGIFszPIxCrNy2cREPYZutqrAV0L9VQT9z8u0tbV2RJGXbuL4ttzw9050CitKFxzMFaaaSv7C0GJj15Wx94+0BraEVYD4/7
  template:
    metadata:
      name: app-secrets
      namespace: staging
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-credentials
  namespace: staging
spec:
  encryptedData:
    POSTGRES_DB: AgCb+jrwhYGuQQSKMmzX/dLFNmyH6Y+UE4QtagAbreUlJWPYPqUJ5OynY2s90TTbiVUJ9FjN4Ktg5q00ORTVniX1uT15yqzSZphtq/QUrW+jV3j4Fvdrz9rVzhQPhqw7ptmei4cT/WNZUJo+C+f4QPwnryWz+jMP0BDCiHFGSHOH8LqXrh7ZKZvIcIbLVR6TXr+k8lh+xSUtsM90C08ffxXVuRfoM+pJSzfIeuxtq5lCaBn7f+25cdaATB8zed9LW1WaSyk1ddce++2cPE1fUFgMxziY2Jy/ZrqmAERVcWWGC0VFDWBlhsaP11ogBpSfhwkK56UNItqEuS8tohLCGOEufgHfbMwe7CTrdkOJAJ5LwdiLKJJGb1+emA4ddScSA0jTtgb6gU94tXuvH+xZgIBX4Q/e45QFAWj6t7CdVIVXt4HgbC3pEBA/HYlGgSocDt2wGi/kyZrzfCpwn6uY2+CsBK8A0phcDHUK7PgI6pSJ1akjnH8vm/u78x8DTE/7KfzL3RopDeEGRcnrLNGPxU/4NAu9+2RY+hokEktG5FZaclzvYjfhv7Lvtce5SF5RPizuFtTTQndKx4JJANfIUOhzPBE6+07CPdkLG6S4H1+upqY+Ql1Q3aWse/Kn/WEy52tGwrY8p15MQbx+1zdQoxGgQ81lUttE8joMPm3Tk7N5CD42wpPnvkH9wQg5xUofZnQomMJLZQ==
    POSTGRES_PASSWORD: AgBpEKd3Ius0kjMT8Scngh6E2X/vAaY6fZGQkmZfu4zSJRPBEloPcx1NkQnnX+dNMOqbPcZbR8R/tKt5poImIFrqfGBEuDyuthhfxppMOi3hlghiWQm818d2Ed+2u3vtMkEIkof0xrqAxk+oAF0q2/gHO0ZiqBcGKLjgNx7xrLzskkmH3O7WCtrTP4ROITeLNGawPS9TVo1RY+mlgFraXinZ61+SMqwC5crvyXbttvuJywhGj4lrrW+6OXtpsAJr6uQJkbpFwb9nqjnjVxb+VWA5lHBt+kFOnlt5Q/qjLSyyBJKF/7SMB33Xt/oscGLZ+cMEiOta6Bayl6tDaKnziyKOr11fkx6t0Qqck4v/X60Q0ce6vqw9QH5r8sUQNVXFDwZCGgQdfl1iZ9JMtmaMvKtK5qfJgzqoCeFWRKVdbU7Wri9a2WHxyskfp1MiSQvBmCACSio+iAgsmN9UqnF1q9roH3GKUtxsXLjP/mlDw94h0RvND1HltAbJ2sm/sPg6vDVhrgrfvv/gHog9Q9VK7534xhesMJH/5Z0kRsHo3GBKseg1IiU9PLxNwxTjaVlo/7tF64keGT6LsyVP7+/7cMr60ITvWwFB+bx+kijwo8TSb09x7XTOLKncdHZ+k843NbIk3NMJ3yYTO8b9BfmeUYpkjT9Xidxhw+59UR2IBOCeN4L2QYwRKdE5FBxTmW+TmxFNxZjJE1qKNC+5FFmvMvlcM9lw+Os75CwVm9clFT5ZZGm1NwDBSKUUzs2PyQ==
    POSTGRES_USER: AgCpOUPhHmmLEvMvDrKf5dEoTc5WS6vf+UnoYTemPJKvz9CJ9apMXyxvOLXdjvYp6gAw2WsEd23SH94NzLSUKswhGRyWGaSpQrEi2Uh/R2HxduD/kEpGxzY6/Fu1A/fUgtl4fGXppeNeHPH+DZdYQkwAUNxHUBSd8dK4o02rJrALx/yb9yk/JeZxk1pRasfKQrkEehWpqXUZ+Msuz2zAWv4StXlHu7XZUIJfPD4PbfLomrpPpKa7I2rWyD/WEqUsDEmcnbU2wD6CAwXJ70tjwtMlJlKdI52/YScNYkp5OAvxg8IU9YB16pzEJ/B/uAXCPp4WtKZpJhOeQEiLEnGPG7DadILJVt3sn8AHpe5K8VZe2ZX6vEaYxdIC4pR6zHVWiydCGlxex0E5sCAL5qak7rbtSGeWKFmMIKSGJftFsEteCpf0vo2ljBVQtLfrEeePFF7D/xUt97BKyfItP7YAZrkP6QXTfFNYK0DniGi/TIVY6RGwrKw+rYONU+ueUj1SA7SCdc82JRpQGXMuwpINhBCaXhTM90ZfIkuSa2dqokcS2gQZwjhoCqCKvyigbIFGzIsJZNxDqt00zoECxjBmVbaXar4ktzb8u+L4YWZriwD3ogpM9OtVfiwVsrSK+77mE4wLnXHw7/9YzO8SUmDTW/QIy7kAAXusp3FqdjAeC0cSbrChJIV2O5Jl5tEPMOjmSRzPBeLRYoUWL8qK
  template:
    metadata:
      name: db-credentials
      namespace: staging
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-credentials
  namespace: staging
spec:
  encryptedData:
    REDIS_PASSWORD: AgAQmzZ/UfF8o755pSTJXlwU13BWIqpoyzq99DVUgsil6heP7oISwm7FsP08/K2P8ycax8L2QlpzX83UdKbYqBJxAsJgGtZrelxgbkuvbjfoLzQeBDoQVy5KQPA8+aG/yPugGD08NQRWszhEoSl+hgd7L6Uk6IhjaRFOBHVYZ+uX3lBgMmHZZKchELSZ9yzXCyNqM9Rces82xxcPnfFHzq2sMbyLom7CMs6Zzb1ZNPTO3quxbXSgh3I9FyXZy+quG4gh6odkjzuv3WgvvxvXwIQANwEshyr6y1f17XixZPPDC1XE1hICyQQkoY1D0GFhG6e5zITkjIbp9h1tHwQZDDG0syJDdxfLeU8jOJWkh9vqRNg8g0fnY0dHgmMgGXxj8E0mLGtNmlTJUeFUJvRrdoVFfXw1j49KpcSJ+pYUZwUMh3DLZ5WR9i3LqlboogzD/3yVSlmBD7Hd0lyv0/VQ5m6t3kiycG7KdmgXCY37fl0Vo4ChDHsyeB7/SovZoKuFqdckuVqjmllzB4AlkDXPvJG6par60C47NowkUXjJLXnGcx2rTuDYdVo15mXh0CHQK2tSVPut11sUTw9xnaAjpc0DbF7t0Ui5JqYX0dYOJhaA+G4/gwAjNY8Nn5QtCWHOfSEmkGwgPEEVHzYGlI3XexVqihCkaTrnWLytRPb9HXWB90PHeEZoS9111M2jb8C5sayssn4fk5slVxg8XOcQNjXMNqm0T/eFeC4=
  template:
    metadata:
      name: redis-credentials
      namespace: staging
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: resend-credentials
  namespace: staging
spec:
  encryptedData:
    RESEND_API_KEY: AgBap9RlwwMMIN5aLGmr5B/aSHQ9H7rEsyrgAupsSliIVbEBsXZldsKKa5soK+1+AKUjdTClIKFnKZaMd4x0IukwLB5CTRLDvvIC0n+u7WQbvGIJBlT9YxOag9/66uQrRSnzJFgdtzpGtXnes4vPGW33MdYfVZ3ZSt23GH7wIpwVftzKjB916Rmi6Dk9lj2+KPL/9EuOlHHHDBpuCVr6hfof/Kvr7iMGUXA8kh1bHSGVoG9AVjIN0dV+WGfeyznIdo80Vpz5t7btRusW//qDQXLp9ZCEZa8ivLnrWssPUuXcj3EB7YyUdeXKAU0WaX3F2Co3l/eHK6oe/3rjNG0I70Lt3iAjdvE0hMRxoC0DjG48O++HLch36cVNwwrlk46U1BizS6HOGFcmFZm6E1OGNlAk5JS3mR6me/Af5jNgyZwTkavsBPiuadfRNFvsIzeJ85tvn8hOOypRn+80gmVYvLBTSE/zfX66iEdYdohPJpq2x+7xGDJrLEmwR3YcJ+K8TgisWZKIn0z5Q51JkvU9jSidDHHMx6+FMkxPGnGfn+/5K9SiiqNjqdXSDEoDveotHCUDteYXNEgKOrAXTyQaAUEJG0I2kXGoB4JOTclP28LPuHFL1AvJTuFewcYNWtiHs0fD6wrQsbIGnznBGw0DHEsQnGUlrFHLa0V60Z0ubWf5F5690NZ6ujpApDty7a64iuax3QIJ522E9o3YxhOQ66nTR6ScVk4fh64atplID9vIR7+5ldU=
    RESEND_FROM_EMAIL: AgDGU5H7LFc4QNyXiO+QdkcHH919jAeILuuaJFwBtPRiaLg3wWAZFw5bCBs0w5EnfXQ2vxMd7ZRM+cH84TXBffXZmyRcDyAwAOrq8mJDXBjvWqlcjTnUS+LFmjMJ2YEYfCn7vs9VHJcMnuutWCTodYW6t3HGr3cOST1vZtrtSzENaCssZBYDlMd85wMM77f/0/ryDiRcsqlVPMRThzvW3egMal6vKhyOzAzui/hQl340DWd2Cxz4k2RmS5KZlXuv6WzL5QB48ngR3bVN3OXF3l0O/QTN6LX4AmOMZfBo3U6y44GHJF/xpW7/RxZ4G/+43Ob3fHR/p1TKrHAMSIPHyZN+rSxMd48zKKlB5Rseoj7Cub3kz/3DbqIPN+pHtenFes/K6Vo4K0pXxgIA8KZFDzm3u0XtVmPVMioltzPWWYNMyUVByqVvm+OdaJi9YC4Ldj4WsfeyvRyl4cDYnXdeLMqonCZeX9RGIAJb1YPa3bASzKH9qsvmPp0Oa3hcwTDpXk1a+UrUxs2G/CERmKpb/geAMTD3lkMshZt/kq8DCzQDNv2NIE9EleThLIDD8V2wkfvTn7SamY7AtbIAcjlI9fDqqqmn8vCBWpvQcOj913JDW0SE8UdSDc9EzntUfjC+IjrBwacCAdGjAfNtXBiEkHKgdivcjxXZI7SWVSasHjrmdXHWtFeOx+37AV8DykYYQT2JIc6Go/TFaihtbOXcILdQP/gp0fzG0Ef4907nrj+VrsxX
  template:
    metadata:
      name: resend-credentials
      namespace: staging
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: staging
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgBzgZi7zPNR+6x4+Q3c907u0J0SPwR50z7q5AHSy1eBUHmyGj0cw7HN4BfXJF7CAcVZwDofs/FU7u/3FYfgsrGMvuDDCvGos8Pju1EYZtiECsQUJb8xaQY5+V33SoLV0yq/LqZN1fuSkiHf9n/HYsdLpPPSNGDV52T8KCy47xL+dqke5vgAgo2zX271jvvSiHtPH4U6LcrVxlK/ZCAehSGp5z3ERnb5m+h8VvwZeTrLlS8cMP+7MNAU5e7lfIejUsXaJw3hx6qtKd18FTX2V4pbNhFqdz+mDLRgNlwINgwcJv3qWL5lJLArEemXvb0k74hx0ra8egw0qt/Fkc7ympaKGk3k5BLT8Un9DArhnEnJf5Coaj0Y6YaD8+6HHUWxocrJ4pmZILvoIShuzEfGGplJmh7Rvxg5slV8IQSF3LNcSxgbPaiy0kuVtJ+U0jcxaQZQkJ2wNGsrLZAUlSvaD7gZVqzCkTfjcl4KrHANIYcYHgOTwScDVDSKq9vnLqHvxHyTX15B69SI92U8yV3m06uNPVJtweQdg3tyPjJ9zZ3+VjrrBFVD+BGkpUbESegictiiGjzzmyzo95yOjhhfzLDT2TnGn8o31l/c5LcJHKzq5CKTBO4U5Q6RavoxtV2ZQJRmjaGeAPlCzTLyFXWuJDa20AHC0uRcEwGCxmb+vagj2+Kxk7+D5i9Jpl1yGj4JsysxQSrUnkfA3P6LXSTv1l4rwiwbj86EyminIfzBiHOaD5Uqu/MR5sEG9w==
    MINIO_ROOT_USER: AgAffFrw6BDqSO7eQvX5mbIGeaY+zgPOJLcgWC9iToLVK+WIoQvHJPqhuLuYenQBAcClSSDewpLxHn1oPuzKd7gKQvjalLzblhwcmqrTy/+fNzo88VBphjQ2coOPcA4XoaN45mwj8lflLwp7qvJyDEXJdXHHTukjImZKFoO/rzKoObL0pZNakmoj5+j40VCkSSnu7bR6ZFakwe3corVmJw16lUjkFFhNquA/OSCZH+4KQ8bNSYRrcroPFc86OLlA41oh+TgAkeOjJldRXbWBBizoCBMmCV/UKdLGYh0fLOuTNLIrY6RhsQSVxmBPkkhqz+r4eo9P6FEnhMX1H88Cka5KV+B6G0CT6Wf+PV+jynVj+XkDZpPIEVLsshhpMl4Sr8P4KjIf1GAso+lzS89zHkaX60yHAWfUedamWjl0Be/xHfQdiJrcbjtqa2ztVomGK6lVK7xrGdQi0QbiynYCz/WHBWzUx+fOzbhhtGGrFZMUyv/bgpQSajCfgT6qQzXPqmf2PDsavJ+iy2hzDbBbmz5Qh51ONTS3hti0HD79kfCdvCtmav2ePZVgCdGPT4bvSIA63sX7NJFbXGJ1MMaeCaZ74/Ff7oIOS60nSeTgC6bcAo6mfpPQBesbcnu47LbiZA61Tplf5qN0LwM9+7GRdq2Ggg+zOwPmjJVnIOGCb+mMEv22u0a3t6iKAqZGR9vwKRnnXit3iF+HE+cWWIBSoYmOWvCFoLc=
  template:
    metadata:
      name: minio-credentials
      namespace: staging
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: staging
spec:
  encryptedData:
    .dockerconfigjson: AgC4YJ/7bAMwspLQdZTYAhKGL39V0Ur2pEixYcYSoEy8+yblEOWl32L/ziJ2+4MAt5wCUlekuMYQfyfaACFBX4M1XtH+DeACC+5UyL4FYse3iRqCZmYdrs1/uF2YMJwKKIWYVOFnlE5xenJdwOdcve8mjesQFZ6ZxMbdGZXXKOsN+ShJBllnLUqQ+VNJQcSkedq68M5vwB09liJ8AGNLXg5wUIvREu0f5ht5lUdG7h9K7sGaBiHpeAgHTJ+16Unv5vTco6iOZ2GNbOchUhzSqyrWSrY3XzVOCqNirN9BFMEvt/BLLleY7rVu2xAX5QnsJWxQigL5cqeBKqmDhdY6Rtmh5+HImMYI+3LzI8Ll9LwV5BbN4CILhd7diGkSxxcykYHWqJU9WIByjWVCqpnJczBuEsbaZUjjIv5MmaxxklZQTS9z53tv1xGmbdQMJvoIK415XfHAImpBOsuKv2QGBG52gSA6Mo43SGkoVbO+Ol4pYlLABc42K7nZnPyXZu5Gz0S6/a7anS4y55y5gAKYeWzLTi7FOqM72ctiB8b04bUo3JMe6GjC7XKpn5423FHZzuNd/eRgPLMb6CsXbnSr3jaKzKdhiZBNX1JNtgYqfkWf7M/yZx+s1BN5/jlLSISU7ytike5CLb2kTJFDmq5Z7xPU/EZor6Ho+N+5exbO+g76f6pTqRbZblmOQJ4gyECRRvTpBf/wnmliARCr1T9tDKJdCDeF6kCVaw/bmomY62fYsVR5wSW1matCjuE4gaOT8gIryuxx0jGkpnWCi/5hNqpkh06z2Gu9cC3ynmUbRu/IE8SuDD/BfhCdomSI+L3zvLnGv7U2SKRkK8DlZsGy3HwDeC5Jha+ItXFQyZsfMyk8FC06/Lyhw6d+8laWPvtQha4y/HPu22fsu1T0DuArSQDYFXjMlXE4Kr0LYgcCgw72DcopeMj2lypAmaZdP/IULX2qMFFpRxjo5Cl+BpimEhX6KczqliAx
  template:
    metadata:
      name: ghcr-secret
      namespace: staging
    type: kubernetes.io/dockerconfigjson
