---
# ============================================================
# SEALED SECRETS — STAGING
# Généré automatiquement par scripts/seal-secrets.sh
# Ce fichier peut être commité dans GitHub en toute sécurité.
# ============================================================
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secrets
  namespace: staging
spec:
  encryptedData:
    SECRET_KEY: AgBtzURIQuqN/fPL9gCyGvf9+nWS2kch+LJGl6U+8BsEXyMVQ50uIs9ZNaljBcMsFdqKKFRYFwNlmKGygjZ8CQj1BtphAr8bdkENJlp5/ZUfgP2KcprvNBPgvFjNtchwWlfNRubUvH2c2GhFetF4kDYmONrYB2Z4/WSDF5CiubLXDI77RW31evs4l9WQWWwtSpL9/mrrAxyrzQTpopVcymM6zl9WzNlwfeZ9fWIAkr1myhxDifry7dCJrmwXP/96xQ1xWB908OkdwCUFTUBZSNotUXaGNR2KF0n5+Iwrs9MwI4MgyhZM2gld4EhNgiheWp+tklwjIxmLK7nsQa3FyXr13VoEnTvnwDLGhDWj0C30x1RVcDtDJm5G8wEJYej2yaL6qlr25vMgNQpQ6mQxoiRnXYQfENgdEvfL8CyyQFqUe8mYi5a5FiZ2uXEEX7ppP6JPXsu3hcys0Bo0RAVAGiTkEcTKH+XQHIOnLPl3sJosgYTdKwauhVqkXUIad5gULFC7ZMlK8TC86hQ8ZmVMIcwkffkxST6/FwmlbHiNcjGggeJ+tuJQa+y7sWD35aJcP4o1rvPTgQJyl6zuk7y0g/X+z7mQIBrXFOQfOQizdfKEj32YNB5ytceAJ7KRQfqLJyWd8W4feoBLte6FkZK4xLohtj1kKc0xVh0g/c//yabsbUkem6H1I07kUPmmTdQUbAdiDlQiQYbsTHp4b/10XK39Ybhy1TJwLlYK6ABxFfROX6ZbrFkTl9q7ydaGGo3H
  template:
    metadata:
      name: app-secrets
      namespace: staging
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-credentials
  namespace: staging
spec:
  encryptedData:
    POSTGRES_DB: AgAZLEsUZUNuxrAvN+xmigHO3DRya4Z3ElGXLHRqGHq/Nr/cQq8I+/IK8hKnvxYYZlgPZD8qKtUST1BU6dIVI7Qn0HkU/ULp9UejHaQekikBikRQrAqLbAI9ZTmQi4yWYui0HCc8AcBMWgQHT+p+UL0D60utW+1vhzu9S3RvPzFw+ssbo7yxd+5lvEdS0Dla4p6MvnzTY7uVFmvuaSFYrbhD1TrijtvJ7AydL6Qwkn9vk+m5I+bHFq1C4A6z8ofNPcQl4DsBYDmluDkRhGovbz1H9Tk9TKaPh15QvxVWOus88EDXR31BdO3uJ/m02AmS5uATB1QV+EEJlODIpE9142/GPmiu18sgjqjOYxE9KDkuWp3IoUddf03H31tOQOADzDo/OoCW1SaeBtdDYZP5wgonptOe5DXJ/boK56ATkouwV6pAORb5/Qx6HX3rDomsTOzSeZN5OGP6vQ1zOj/+3OJU4PX2J5x6Oyy7+Cx7lUc+XTwt3TiJdInRfnW1b3OQdmfc/Oyfivt6qFoSksLIupN6/CGl4D/M9Uqk+PPNNi+RGV4lWcXQBGDsr1WVj1m3qYC40tsjhpvoJEy/sRT84SMwMNbF80eqp6LISs/ymgCjo0JMQ6ysDtUld/V+UWDtdAE6gBHqSH46PfDxYXpZFbm8PC4Myw6l9eOfil/PPIn2rxXzfGhPjOgEt8nTCrFgOzFymSMQlA==
    POSTGRES_PASSWORD: AgDJF2uZMU3ocgZ0lWo76hx5ET/ukF3S2J7o/k/Nh3qvN78sQdO/GBM0NJj3BoQ4unKQ09kS5pVRCJCAjuznqWK8/DruNwsN9OkyqwDoN7iUzY6+9J722elb7Bl10VC9kSMQrA913idy3+6QWpg7vFlldWsGhISs7cqIE84p5uk/BSqTHeIkvOm9VpTbHlzsPO7+10SiZbpwUsBd3j7O4eXV3R74Blq7AlRcIDkXmWFpHLzHv3k4I6ZWLeIHLnBa4kKWi6WCMY+TCZvRJf4tz/JIodgKtRJ9oyC/PSurSthYGdY3e9n0NIqYpvDZuBFEtivgacHU5P2rNSYekjpC18DRXt+N57WdQOI7+r/2EJrRhDy+tT8+XaFayR/2QtybLwRZ8SAAlbI1ckJr4qdMmyPSR/i+rRYsr7b+J4usKi5VtTWDitOvlJapLnNd+4MxW66mNSovhjLdpoI0JMNIxJQ0RiJs6dpn8dYl+zK0GUy75eJVPpCeI5mjdgbsDWNFowx3MShOcKd7oS377xch3aCF2Sx1ZahY4Q1ot6e9ZTq6AmO2S67pXCQbo407OR1D53Pis6ZUdToZqgiGy2KSXzA3hVjRmmIEqMO7G5gtmDXCqJYKlqjz46mlbu91D73AwjbXQsTfHjFHLsDVy5HOV/8vbL+fMwaTFsDJ5wiQqqYACfeKPdo970HaWE26aConOPL3E+5I46D8lUsTwUH+JaI/IVX9BZzPAk0gUq/rDdvnWGnfmAkh0kLznyHf9Q==
    POSTGRES_USER: AgAZPwU2A/euY8KsOALJgz7gnbfvDuEwVLCCwGL23OFZwYlSQ3uKfUOG/dEZ6aJf1FsDWRmmHUnjkkJ3ESCY5Qe+ostNszsT+TVJftUuVm/ToPap9TL3pSl9coRWtY9WZtIuSmC8cZqkQ84XDwAGqw6eMU2dsqVYLI1X5DuoahWm6F0jNMoTFtY4gpR3Q1bYzw4r1wA9vaKAmTKYTWjHwNWyRmqZNqvYpUzkF7X/40N4q1q6g+NxS+Knpt3TQHm+2PC6aeQMnO4anB0516ryM1sA+d9OFRFxU9lovBKO3+ninj1MmLlHfxhkVSbZIMSWXRNzoNbaF+vNABv6pesv6MIV2sRemiGoDDhh1fl/kR0RWc7eCdTV8+MPGwb1djzVPXhh/EY0ZfQGU412A8YolxsDIa9ZxqPxMQQjl0ThX+CX/dJKu6s08p93XGemmrxmy7OT99AdY7e0aA6FS2Yt6IWJzsA1+w4YtGgI+wwZQIz9JIbTLmNMMAzyD7YCYoMkzWDcVYqwSyCxNUbCSFahQgvLAhr7ltVl5VSzryTkPju7fDifNXFCYYcmnThsPKkfqbL9gYgcLmiWo9Cb1h31CpMWohYhMFszscjS1jm1Uw4awfWcc8QKBi349AX27JX2j6wCjAerJUjV1Ks3YTZkZuDu+dVZRyBMTmEKhPuHMolX7cOaYlImVIrkU/wir1kLnRQEadKWnLFjANcN
  template:
    metadata:
      name: db-credentials
      namespace: staging
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-credentials
  namespace: staging
spec:
  encryptedData:
    REDIS_PASSWORD: AgBZxBvK+MI6iSLhH7J6WRgZPRmDR8ZQSvckVrOqwpPBgChFx0UIBgk3seNcoqImmJEJpyuZp1ovfgwdAWth0TfI0e5nLPyMUz7Vfwa6KS+2m/MWdS8vjG/pjvIGQ850xoInSXMohRNmTNL5ozKcpdbjxi0CzL1Aq5MnPqEuS5e37asFR9VX7m2KY050Tzjf/pY+wpcDpG80jfB6MhW+01i6aocOlNSZ5oLwnebhvvud/fwpFxWx3RC5+qH99PNaSoBA1TRu+5mPocMrA7apqvwgXehcm3BvM01GOI+8Y44OZBH75mXPPnvygMGPyg3Q5WJvLBfQ5gSdBATzjIxdy5zdKqKY5dQITCeHTEzdyMuNoeL4Eu+GE0Jn71YfXx8RBU71pjShpIre4Dqj+PAcwUACJOJnsv9k85CMBv7VmpBux3htzYtiG2sZiHzpikzXX92APup63qSXTld5w4bVeCIp5XBpC+BYkTLG29u979Lep4bQAV02QSLx+18kg2OAvbaDhd/WlVnF9Jn+XWHg3EaOOyU21CCrT42VzQZMhUHGhCBcWarXxZNVUJCDE/ecEKajor7uZ6B85tc0iSTsvpQdY9DrTF6FdhexN8kZCloz1mgP98G2vcfi9s5T6ljU7Ac3IF5JZ0i5KgR/brjUFqub5VKW83eCA1DXjRAflRtGhR046cV2htUOeunTugvxnrJA85CgUzdOUeEWgeYVScYxhHbFpmRMxdA=
  template:
    metadata:
      name: redis-credentials
      namespace: staging
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: resend-credentials
  namespace: staging
spec:
  encryptedData:
    RESEND_API_KEY: AgA4KYx/jj66rwDimaUxm4BRfrf1FrJLc8GHlyjbEL2R3MY1U44s7CdqbUukppTau81OINm/HpZA8WAChmZuIYfDg/Oblm6iLlL09JIEAx3eNDkdJXW3yGSps3Hdmsr8XH9KItibIXELcTatmIztrgOAIqu4EuYoclCbp8mDslCzAmF+jQgXFH3Fl7N352w6OSXV3AVqjhwZG/c29+tKrU4jlGZSZozqDM+mG5RGI0XeufVJHeGokA0FPSzenxj7TCpzliVRmfUOx9F4roPsWtCW/ea+bpZQfx1SD6crX+20Twj1dxedLaEoQ9usrCm27KNNRk65KSNfOdHeWN5JL11GTpnPUVH6FyKtNAQLsNCRfOHmqxepU5g1cMJ8RETs4VFOoyJASaiXvipj1kZ/fkQ8+NJ2acNy/95bqrgW4bRliClPKc06ILUjTEh2U9Y/h/WNQWcPCe7A1OheoVFP9Lpxes54Fei3FgRDLwWNFYh/7YVdWmGJ1zoY0CIYa0KHldugNxekPT1D/kupItHYPhuAl/+TshD6eISJB5QO3bM9tILiHcKfBofHImxo3qVvZTlqiL6pD7jdaUjPAkUx+T4FGlH7KIjgd91Ek4SDXow0/BJVm5CJlW8PmGiUj6x6AfarIAQxfAJA9jvQtddaiXeoTclbzsVoivMovFAkPidrW4J2VPDVIB9itU1nleNQ1GLbKqmd5pNvUZH1MPssWVbUNAchi8vBX1t/q5ceMFVjFHEjZAc=
    RESEND_FROM_EMAIL: AgABip4fTs4VIkzr7s7SVuF+1DBP5ny0jxN2XwMJ0aWL9WxSSaJ/XH2x7hptI4xJo1x4x4zpNBIiO/3ymIXfLvhalHWWZsfbOfA9ymC99ZMO4L/UOROm1+d5s5bA/Re+fUW2NwRieerdiVi6U34i+FZJyiGhQCsrFt9jKvpFSbeQjanDkhXzVqmLjfbQGRlZK8pwPyYwnLKHUIEPVsBS16FqHnY8adfWRMD4DGvi1FH1DpnZRZuOqLlxK9YUu6qTqUja4sQt3qIk9TxR7LFsDKTCZsRIsfPybyI9unqYeF0+4YxUOnr5BFjWdXrjUhYxMnGzkwEf9uuCH3bJ01wqvvtB7Rjas/3qUsD4whxwERatG2gRiaHtfF2HNH9YUkbn5nh4Z/7qPIhuSxT5HVC6xn/TTdxKWTGK9CesN51ayypiRXJvFQmeuXG/IdLyZtqG1T/keT/zIzeM/vjMvppUkmqDGLeqJQadoljULb+opdCF968JX6rDQ+JgLdceZQyg8lf9/Y3uaH4sLPL25vpzToK1ViZ8SiLUgDgSrFjBCm4Vy8vq/x/pKoSUKFULOxKN8Tcz6pI94HMjt8RANegLH86MawgbbtWzDYTP0rsfk6aW/2+X0wX7IqcD7odTm0o17K1ssbWVS7zs+x8mcAPgBx3DZVN5tc3zkzEjOQ4GPtz2Fb2hrrsaFB2nJljxjH/ZnTAwbYnhre5UmFg1bcXyYLgBoWTB1oCU6p+aP6grou7C2CQL
  template:
    metadata:
      name: resend-credentials
      namespace: staging
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: staging
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgCbnnwgk4FCByHmdUvPpORBkx9k/FHGOALCzpWBUyTjdOv7drkCWD7Lmca+83AdUqZuRoAu2nBKbgIjUbESS1UD7slbQg2M/LTrYSdnOF2SKxhjlHLswyK716srz/6fQJoLLUp3YPdcFW/oew2H7bowHdz3SI2ItbPlpAj1NYXcEpOg5NFSRc7Xt3juOWTX54GEESp6iyUNc3MZIW+uRo8T51wfntUPuZ6n2TGzsj1E6OKXyHVCy2IB0mewCa0O1nwJd5G1fQeTbXaLVpTnJaRgw0nUEtangOhENUZdAdmbGxJhyXpwzpSjGv0zduaTqlaJnXurOWUTeQsrwg+Dsir4EBu7gG0sJUmUmUNecLlIMyhdPUsf6zBfqtKvgZ+8xWAWf2weTUK1Q3g3ZJ3KvklGGmNZoOog7g2mUKZ2t65/wWt1FauSrs1dDUrZIglvfDl8FGulH1BTwGwux2yjTQgW8OweNkTtou232T523sCHOE3fBtdNaESw5wV96BU1Ul07yS3lOfIfQGexbraWBWSb2h2W7JcglvjmVQV/pcelycbqQr+7Av1RYIxipJl98xaFoQEjLCG9k6Jo8YC/KtfRIHc0eaisD0M3HqPS6kzGLg4GMJXpokK+LWCLaxjrzZgVeoBvXbg4pLmjqt5lRUQwVmCnkuFypqZeoPWCDtbmEGGnu5FVO+DmI9aYQ4vxhslbv5zTnNUSBmRUYBKCW+DuZKuQ+lndAYuHsZTdtHYGYS/xEgtt53bDHA==
    MINIO_ROOT_USER: AgAYhJaz9s6mPFo7duji28ZeSWVA9nYyiw8TBlWNtnTVAcUCO0+lFau9NaI15FjnRIgeNcyuHxUTWQixLiPGtFy9UpByvCD60SIN2sfVEZlEjPF23an/j3sNvTH8hfkoUIeD8TKE6tv9iTVIapa8wx9z2f4cfZgnnzG6k5JmBpSosinwV4Z4b3HXkCCf53O5944iW+kx0aC0aIcW76voZ1kYrPY0VK1DGA4TVA1IsoV18E06NyyDlerEkFX4L5+qzdcUz5VZuEek1L7QhzX4JyofevVKKsnqVIUTJupARQDGcVV+t89xh+p4tDEh1s0G0gEkkjkjfKDvGmjv9WVSJCpRwnMxOwU0vRs/SAw42lgjAH/QL4X4pKT66MllOjDag9sLcYE1ZyWRWHl4JKfzXj3WmEz/v58QIcv06QaDx6IrUWYEmv1x82E5ZeWkkuMSrO1jjH/Dp0ujqhWId2lJyYWetHZlThIp36fpKyzXRUPaZtGn3kWVoI1CU5hv0YftFc9RUWrxxWmQ+g4dNzdPKucQkDFlZRjUtchVdb/rwb7wAktH5Atr6hFaSpGnLLH2IKKEoFMvpS4ClKJWrkSmpDOfuTyPDo5OZadWw/aoGMDjQ4qvGIgdjJ86ASwcsAnBcaAz9+RtlLl4PKlnuNT8u0bmdqw9jXRZwTT6vU6HW8el7DbleqWHkiUGemySVcDsYR1z5jt9/eXuwrkepx3HnrSga5D9hcY=
  template:
    metadata:
      name: minio-credentials
      namespace: staging
    type: Opaque
