---
# ============================================================
# SEALED SECRETS — PRODUCTION
# Généré automatiquement par scripts/seal-secrets.sh
# Ce fichier peut être commité dans GitHub en toute sécurité.
# ============================================================
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secrets
  namespace: production
spec:
  encryptedData:
    SECRET_KEY: AgDbIF6GdlJkkn0QZUkSE1Y34uPkG3KrUhbvbaznCeV6BCJckZM+h+pL761ruvEmQSxJdntgo2y7SOlLw56+Gb1wfct+Im17S1mk+Lsi6G0NZiWcSpg422ZO6sIgw6JsnwTPmolPK1l3Q5RfDus2MwyXqE3lN2YQk40UHTnlGpfZi8qzjEOOUfW+rvbq0Lgjix8BtpC1yOpRSnz9C3MNcPRxjcTYeP5VpEWL5Rrn8CRP+hWQTZRS4UCYKMClFIGaNrS8+pLcEh5QLawJuPdjTK39sSUIY4RC5gA4SlnkWDIWpnNs5LRqk8gSXdLGhnEg/2Va6JlNYfr3L2uJTQPrjisY4LuSv9PCo1sjvWcgmpdhdlHgS5hJNpVXt6WUxabZMwYegX1iOmjvLr2oK8W2GDXwYdI2Splk4BEcqcoV+GxaDY3MDguYPJjaP6fmh/l7ZGt79ZQmYf3GvW6Orq5wfbAa+9Rom5CcItik46YTIf/i1POxKDziTnTt4cr9eFkDUcTW3vttbgljWQGyJSwsVK4uNNWSZuLypgBpJ9kEPv+JA9fgYzm2QUFeKzghrfN+8q+KOM2Ki2v4hTLZ6MjyPhtJd8UBupjJVK+yTXT1nhoxfEectA+SYJSGRuxhGPw5oCWVCYMl7OIKbuQB0wxFukry7LGIpnaeTvMdFwY/lwMoDLM/RDnM/pATupKT4sD0qcUP93Mc4/MKhvz3r7nGuI6rnqsuOM9YokBwjyWQ+F/TnqcimWQu2OycjbG8aHmOnbYq
  template:
    metadata:
      name: app-secrets
      namespace: production
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-credentials
  namespace: production
spec:
  encryptedData:
    POSTGRES_DB: AgBhvWpQyZdjq85GgN+3R2W5mfd1OXS956O8atdAYRuuOMlASyfEJ4fOOPPPjpLg325gBSmw9MoZRKLhLtrOd0Qct61fpXwmvYqQq/dqdE+wlRIC0GU0GX4xc9BLVhofma5k0BRrbgBCsGQeJOUPhaOF7Mg7fP1PsD8QtvltOZQ6i+gf3B5DkKImZSpWHBiOONToQr2+Xlnn/kL85WPI63/wQYV0KJWMfYISQ6CyWN6YdO81GbM3FTT/bklRsYh1Q+YUBlJE6dj03w791cWATLvblPmrjAcuQyHJcZV7UXAlJlUvGje9p5VTB2eXuHLynL8Zz3xn4mSuDEun64pN14Ket2WXFsXQk+mzGxLvzyY/qFbB5WiSFfnsH7Zy3fEbgS7dNaL05ezTO+/eAGhLex4ks8dZ/1r8/xpt2ut8bBwX9zDYhZ2yIxCOOCXgNIlf+kcjav0FtcrRMoN6JdAPhzEosotf53DmdlQhCQDmFIEUuKp5zPy/phBkWb8X6ZMOHIJ7NkLr5fBJTbEn7Re2EatAQv6XJValP7/I9FIUkQkfHqVPNWOgMl7CAG3AKeykmWJ/+e+bOmqY3ZO/Uj55+rAf1T7j4lnVSOGvDGZvJxSicAUmRWK9nCltPxQXti0mOsCZA3XMNZ1mR1H8q38IkXiZ6wq58a2D+RY45lxIvNk/cZZ3iIiOwpG5NDHIGP4CtWaZ/SpnPw==
    POSTGRES_PASSWORD: AgA4cM00RvWmGWSgQlNyW76xZHIk1TddQic2WN2alhwR6tFcW0TY/fRanzgT7sxWvA+1qsqrW8Vwkgt0302fObiHo+q3/kEU2V0ET6H60/c0bZmfYoaAHhxYVJjuSVEwPJpya0MhHD3AKvEascZHihAWKjjzvlej1t4ABp80Ecf7iIeSHfmBQZi5ABO6ui8l3HGTwJcXZf0bLUV4bigoVpu8NHvWI+Il3WrCjDHgpogaU6yPKilTJEnHES7ojok5W3W5o1ulFh2UOD8Rzn4WNil01cUagqGHiBReqVYZl8T9MY7oTHrYgyDXo1hfVp/WM5TbBoq2oF40Z+mDUuCJ/ouiy0TDn0FciOtk1FekfAyCzWyeMgCoXQD1JsaCF1bj/BsDrc1O5JmOcyucujGwbw0MGmqwvSPhBCOllNF5GbONXHWwcT7Fhyfjuh/w2xrSoTmqD7faafPVKekLCe5OkD1o8F0lNyNZU+Bt6ewhNGO+hxrUKdG7hDiRnjnIqJCjGi/gi8Q/rwkd2CWl4U/JQ/zTwl8hyofHZ4uFC7d/otcvIU8QZySvpaXUlFE3fu7vIdJHLfmXQZlv0D7nCC1MbMhxJfBK5a1APzKdEnknibwl9mfjLzt2OlkjWu05hh+SKRZdB8ZKV4TbXzaHLeq4UNCpG7cBM0UWaFrsjkhRtdke3Gz9MKHha8DUcjhdw4OerD0HsCAEVxPMu4GXKMLfGLHzRzN/c5vZbQUb6p+GNT4S5ziqmFMTYvToOAjrNw==
    POSTGRES_USER: AgALPgrHF55T/erK9hSBqI0NehFHS9vxTA79vX1ud8u4tMhK4XmdITgpFQPjrduAC1ldc4GzLUUO95Rr3Xy3rvtelgtny8d6Wc0i9959iJlz2HCXpYE5RJ8PjjzWlR/O5EHKPONRBbHgOpdUlFRdoIvpbw6QTQdINHm6DDvT9Ck+G7UFh1vOmDJjN8XiiGSLPNnT0UGaXJFSMg6uCO4in53qikYgTmKLCa9nTN6Ot8ukzjRbr4Xj7gtNJtmcL6KvLtUb2W7m6ayeLzZWftoL/USRANRY12fT1Pt/FjdKK55shB4RicrV5p6g6svaRbJXQDrk0eWOsTEfFY+BFtSTF9QWMM/Ik28zGfChLacxtQ/o+sSXgTjKVQP3T4mlJxXZx1adnIJnDB8KjFSsKPUzyhJ2Y1VwNKgNi12mvL/cwl2p+h99Wiwr+nr/Om5bAIo7+2YDPMgAazouTRfuUzRmEWNCKZnfuBRgnBE2OayvKp2OvI+jF5S+ASGxNdpMMB1ibToY1klPquNHxfuSOz1A1dEIjVxNad7WefLo9idAZH7U7yZnWQD4EXMrjDaPSb99C6KSDuZmTJlakR2XNAk+QVU93/CAUGRqGJ2HC48ckje+4JdpP8azYsyf1M6S7Wt2r5Suf6pBg1MKcRe3xjM8j2ysOMUXxRJnouD7g9KFDrC/yXODgGEnfBXmeSu+AsAQIDDRcPRDa0HExWWX
  template:
    metadata:
      name: db-credentials
      namespace: production
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-credentials
  namespace: production
spec:
  encryptedData:
    REDIS_PASSWORD: AgBIHsAk7LXRAboi9N8CTNaR4Asvx7NCjxKmu3SmKARxECS7+3n6a8Fz+FZfUiGPLWH+/kgHQfvGIQveevfTjButoEVb5Vdja1qWPDtJ2jWrQg8Rroft2Q2dnyNh4s3B4q9Lx0iUGkPNebN/SOvSI0ewNk6iNOt9NZjbfCaf863GpGJtyOUpZ6UPL/TntPR8SX1DWQRcOnskd5YfZqWj+CmVy2f790jPltMxb6Kk1lZ09KWpgsKB9cqbB9EbBp2LpPq3ThHhXQbYZSboR9laGax8TF9SCvypCNh99yrnN4Q4nb/EiBpbYcACoSNyBy+XCJ5vzx1XJY7uQ3272YmWX+jxVa8BiOPwr9xPtmubW+V7j69KBkC+R8ALpLNUriMKXIazMjsP7rastKSssQLAcoNB34m0wSuRNgE+XjCVkjhXNlilk/ry+dS9GrpUzOvqxK5Zj/wuHE1Yw8f0Djq+F8DdZzaPM99/RJYxmGox0gbQ9O7JPFDpZMfrMM7e6VLr/n6PgE60uOg9F54r5XX8zxhSBRNwv224GJx+YWSydUG/zcnlk4BmScgBPPl8bIXQTRprjkScaPlB1SREF05jShXnTTWMPGpgWRCy1NUWOjhnQKYmfA4b9+Lrr1+2xTr+ooTtduSIcnJsqmHLUx1/fYIocwOW2s1nBEjBF8dkJHoqzyhEmlPsvzohLqCu5cDab6WzrYDGcYbMwYnjiFLFI9Xh+7eVThuyXkQ=
  template:
    metadata:
      name: redis-credentials
      namespace: production
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: resend-credentials
  namespace: production
spec:
  encryptedData:
    RESEND_API_KEY: AgCs7YREGYtQnK7QU7bQ+ogcyWrXSfbHUAKSkPReCzYsEkBqdNTcdW9G4DBPsujMBb2IZsVSlTGgVp0mLhw+63NqogjFbslNQisu1dZ/uIRdMxQDaxuwroa26uHdr1XaqF7IApWZXPv0ZGaI9Vubh+lmhfF+Gm+K/6dDXolFURtrA8ZW0xmG9bL8qfuypdYrF8pd9jJD4Md4x3qSBJtmgocZVDm9yA8C8yVaXt4yoZDzBYkugvc4ZiFTeMwvAZe64lcVuOUa37vLO5xTwRa95C8G3oVWnbTuWdn/irFrwl3H0zycexIGqcAz2IqmGDsrEx/cbZkUQtyLTBS7MB5Z8+6iXRV4QQQ99cLjymDisf+N5nYAbQ/udG/fTwfiSl/9eUFF2Tyivfbu5/He5DyQg8nBnKHEx4GytpdrugMuT+SuvIQRd4kgPDaFsODpaQeeDI7+BoGqLzYbX49cBYWCVmscJCo+l+bJ76/ZkcIKq7sWostcNMSy0hH+wV+f/Czur5fA46lZiAzbFjOaeLWwq54U1Gd3UZ+w/Dz2G5hP8AxhMWkKV2KW9RpBQcHbQCzZkpb/I27N3DnxKHFACJCyaNZOazhETz5LVgw6d6HGnJ0BN61Y/H+4iby2Ph/JEh/kmV/VZRbb8HK8sPZGCrBEq+SMyOLd/JXasDcMO/QM0VeJYtNthgkxFj3gr5nue/n9s6ziynJa8Q6zu3r2hHT/tHVimpZPG6ztcHZ+k0yQTug/b1n4lr8=
    RESEND_FROM_EMAIL: AgCYO4Jrw33+pTrLyajmXNoftD4ip3DeZmcOO7ViJ5wKKgF3d0LCiIBWi+18m6FUCYy0o3ypCu5UG5TG/Dml/nIwNkMilMpG+/sjiUeVh+7ER0o6VT1q0bGQi5rbdo1iHUVE2Fbjk0gSnI8FqpJ57voR2BjVIwtYR+C5VZOyjODmzGoLr5qfLpmQBKWFfCDTHo7ZjkXg93/qiyp0spH96glMudU3MlufWN8JLoRQINo9MJVeMOgpdD5HZhUA/EnzbmKWCqSC00Z9OHPBYfky8gnASBMTrRI5hqCv4/w2UlsAcNut7GvHB+cD3zEPeXTrd3ELGAn+s+WWWW2/OpEMabjLlYnw6ncpQhvzxnArV5D0Pn8sHTtePb4Nbaj7NZI8DR5frLceQc+PmUmbMhFijdcjY/UT77FOltNUiLZhy9ooN4dJ0JW+PNimTdTvquKV9nhvYzYXg/oMefyQTGPXL7M5YNhYesXVpbmumm7WJv6Qc1z6YfG6Y4bOXO6DQ39kAjfkkRHF82ZNpv2YHSpNh8Kw3hCXDhAcoSbsyVguvJTDzyyPqM+i6gnQq+DnUYUxLZql0kIMC4G6/RPRNOouOJwFnLqta4ViKLEfsG+6hRTVysYNO7RuYj68sgAzKDtuBAXE54rd/VI2AQkGbX8JBtzcroAVavd9coKCvp4/7uwYU+SVlbw7v/rHQ9lw3t82CKu3VlX03BZHioaRc09+Vr6eINInYdYlL6vJEiJ+yVFWHYSq
  template:
    metadata:
      name: resend-credentials
      namespace: production
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: production
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgBxlw0pD1AqdCl/EMUtczK6kofHU12DRODyNudCMXIgKJim/XYFdbwalbUQKQ/ptltFIf0qzVOmnx932iVb9VZ8Ziit75prx4gNgvvgr4kyAjs52Kzfyrb2UfPAYTMHw4Lo57yyNHIStvy7bgvraTR0zblTdVj23RodaDJWTm/ZIRclIsM5LS4EMZ27dy/H1rMB7BCFEBiLQrk0JDEsRLKzbrQeXGEONimYBF8AlPpm2eGWNG7p9mPTfL3RdCbLjRYKrYAiKjmwdMtF10JigAdX1xJp6qfT/OMXyxppPrE3xpH6lGFRPBM9m8Za4fMrWXzQeg4wyA612nGltDjpbcfsOBOZgsltfYga1JZLpx74JwwQscE1HUAExYqSGE49P/GtCMcyguL0Eouh1Ex9pVejqeBptThmjCjEXHMG1QAa9Rq6lcqOZVsOON8qGNhNoj/X9KsNashSXI2ZiaqKaXU1CeAyxFTVTzlG/5HX/QCc+FHaMSH1zcDMV+0AOVR9LSqRswrgyVlnsnAHHOGl4Pg+b8+8Q++8KSe0fC8ky51qVcvOZ96MqM4ZjEQMt3ks2ng5Z/1+WoMag1fGnVM1Gjj3uCoDN5Cb734nCy1aB9StRh3VDs+gEnApv8AI5A2SZsDHlZnHqjOaIZAHeM1QafkTt3h8naVX/yaM31qgoqxdAHTChLIUGoobgYFgPtcFjJHHnfp+YvnyxWlNW8bKALaUMl5jiBscvzrmPXh2EjQ/ttqVhynlU1NIVfEJiQ==
    MINIO_ROOT_USER: AgAO0BmxzI2bzGkZYJIKE/wsebjfQsUD4QWncy5GvMGQGCCDzi2TB3wyBwLjKQ5Zb7p7zd0s7WmxDtQgIqL0KTUDJ6XU2TUnLv8Om6uzLGStIW5kDUR5HrRlwgsDCLfEacwZye1Y+TDdLRIaMSlI2eKK4JS7n1GbnpmZI1sy9thOjsB0JLFMfJ8DYDiy726JsDv4MH/ipx/SWNb9kDej4GNyK1oQuTsOViTIj/PnZPujWqr8uwFiPpGd5Xp1LtanMbyPFTkMbLX22wPwgbt2SS25FqaQbNfgyX+b4zpZIC68r3N03789m/0S0ENnowQhjtH51zIE8yIH8kBuLfgG2vz1O3S6Y8PKVzWlVC/aX4l/pa8N9OMNZeJB/ru3SSj++oacLyOhZOvVhJwLU2ipxm5A5UfW7vMosTF1ThtY7WsoYBRjwQJgnp7RzLkAmvgfEVUxAREJAXgfjWH9YCRsfR6TUj652YWPJs4WjpgWNkw4DM04VgkzksCtGxJkc+vXfsrmA+/GnU+tmSIkzNzayuD0Uc2ECEJ30MyN8F+cWXZk/uBexXaqUkLpggonwZ8KLQUXJeG76o8DtgvwXw7V1d5hoOIep0YZcimCpH001HiS4vvjprXGrUJOqAiDILiOJUPo883W8FitJhiZCZmZfFMYRuRYmwtx5EnaYbCBj6kQR2eJREgPA0DDIApXSMBkenzMjrRVXydoMcHGy3u2ct2yjQp//hH25oY=
  template:
    metadata:
      name: minio-credentials
      namespace: production
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: production
spec:
  encryptedData:
    .dockerconfigjson: AgACcqKjdj/k30k4AIFHxD3hQNTQQx2/cK/GKqynuevn9RRTG58K/uZxRIpDAszq6jD7o/AgdHr9j3f7aVqJ+AljEwyowbTLvMaGjNkno76EzFEUkB/31fN4/Au/LjrgNrikowJPvN0UsPyo+hXh2TOlt1pSjlgDWRq0/u0JZgZ0y2PnIf8V6kC/MDeSQMHQjnSpAZovBN2GWFtSdFLLGpJYaoyH3NWsP7Iyf9wk0igvhxuuSBI+bQsop0f4gMc/MYfuv+/ktOpFTRxhDBEi+gm0i8JqFpHPdA8nEdwj1bxEVWZPurGfSJ8F/rBRM1Z5EmnLp8VbN80p8j4BmBSPzc55w2IwwYNQbaF02DWjhvW7kDmF0pErrL0spPAN5XBZiPPM9LylxuSFhAl4y8frM2VDVkXyyY9BNNmsfTYbMIOVIwBhnkQi1k2vcRS4VtqtqgBwWLb/lxjvBVM1w0L9jTY5WhMciwBXDGAKLqnxScsWtdKrw/9eaqSEuHZ2ArNxq4q0+hKsh48eUJ0Qz1f78nTUM5GPHScDTmWhjABvnuSRj6NI8pJY1+gtE7b/flmVd8NM3KcaA5vdbzMRKHT5Sb4hwL2VDdYSg6qI6UW65npp0A2ZieGkhjQSzrA+diK2SJ7mDBO9LFCpRvxcGmMivnNDmYl+xqTBLXZzo+a/7W9YUy2Q4UYtmy+Rci7wnSVB2DUnAvZzDX7EBkEw6ObgH7WQWiJB9rH019sobayAmvzkERtSoIITuJB9hYVf7y/lrOzlyU+7slsXk4+TqbfrDq7T58XA5D3Vf5fG5n9VHXlrDJq1reKRQgoszVAu0SWoIBx3camjhrilkNO3DRZcGbzlwETN8krrkr1Lmk5FFC2iKvSmMYOpf78JLekarv8eVmZ7yq5Lk/Swcx7ilOXLyi4HC4eoOqWicfsce9DHmXCG+wTwxyVR5BNkEhnipTU44kCyz6Iisnjm7YG01O5dxMto4CxzdUIT
  template:
    metadata:
      name: ghcr-secret
      namespace: production
    type: kubernetes.io/dockerconfigjson
